### ISSUE TITLE
Status 503 Unexpected server error on Data Source tab

### ISSUE THREAD

**Issue by zhukovgreen** [AbsaOSS/spline#1018]
## Background [Optional]
We have on-premise server installation on AWS. The server is:

Version:
0.7.3
Build Revision:
b16930c
Build Date:
2021-12-06 

Today we started to receive the issue with the Status 503 if we click on Data Source tab.

<img width="857" alt="image" src="https://user-images.githubusercontent.com/10520003/153163114-bd67bd87-0e70-4e8f-be9b-d21190118e4c.png">

## Question

Please advise how to troubleshoot the error. Thank you

**Comment by cerveada** [comment]
Can you check the server log? There should be a corresponding error with the same error id.

**Comment by zhukovgreen** [comment]
@cerveada Thx. I'll update on the result

**Comment by abhishekshenoy** [comment]
@zhukovgreen do you see something like the below exception?
<img width="1189" alt="Screenshot 2022-05-25 at 1 14 01 PM" src="https://user-images.githubusercontent.com/29061454/170208738-284e317e-dd4e-4f56-980c-6e8711971024.png">

**Comment by zhukovgreen** [comment]
Hi all, I can't login to the server, but recently we're receiving the following error:
```


13:30:33 | 22/05/25 13:30:33 ERROR QueryExecutionEventHandlerFactory: Spline initialization failed! Spark Lineage tracking is DISABLED.
-- | --
13:30:33 | za.co.absa.spline.harvester.exception.SplineInitializationException: Spark Agent was not able to establish connection to Spline Gateway
13:30:33 | at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher$anonfun$za$co$absa$spline$harvester$dispatcher$HttpLineageDispatcher$getServerHeaders$1.applyOrElse(HttpLineageDispatcher.scala:118)
13:30:33 | at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher$anonfun$za$co$absa$spline$harvester$dispatcher$HttpLineageDispatcher$getServerHeaders$1.applyOrElse(HttpLineageDispatcher.scala:116)
13:30:33 | at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
13:30:33 | at scala.util.Failure$anonfun$recover$1.apply(Try.scala:216)
13:30:33 | at scala.util.Try$.apply(Try.scala:192)
13:30:33 | at scala.util.Failure.recover(Try.scala:216)
13:30:33 | at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher$.za$co$absa$spline$harvester$dispatcher$HttpLineageDispatcher$getServerHeaders(HttpLineageDispatcher.scala:116)
13:30:33 | at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher.<init>(HttpLineageDispatcher.scala:50)
13:30:33 | at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher.<init>(HttpLineageDispatcher.scala:45)
13:30:33 | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
13:30:33 | at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
13:30:33 | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
13:30:33 | at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
13:30:33 | at za.co.absa.commons.HierarchicalObjectFactory$anonfun$instantiate$1.applyOrElse(HierarchicalObjectFactory.scala:43)
13:30:33 | at za.co.absa.commons.HierarchicalObjectFactory$anonfun$instantiate$1.applyOrElse(HierarchicalObjectFactory.scala:42)
13:30:33 | at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
13:30:33 | at scala.util.Failure$anonfun$recover$1.apply(Try.scala:216)
13:30:33 | at scala.util.Try$.apply(Try.scala:192)
13:30:33 | at scala.util.Failure.recover(Try.scala:216)
13:30:33 | at za.co.absa.commons.HierarchicalObjectFactory.instantiate(HierarchicalObjectFactory.scala:42)
13:30:33 | at za.co.absa.spline.harvester.conf.DefaultSplineConfigurer.createComponentByKey(DefaultSplineConfigurer.scala:142)
13:30:33 | at za.co.absa.spline.harvester.conf.DefaultSplineConfigurer.lineageDispatcher(DefaultSplineConfigurer.scala:120)
13:30:33 | at za.co.absa.spline.harvester.conf.DefaultSplineConfigurer.queryExecutionEventHandler(DefaultSplineConfigurer.scala:117)
13:30:33 | at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory.za$co$absa$spline$harvester$QueryExecutionEventHandlerFactory$initEventHandler(QueryExecutionEventHandlerFactory.scala:64)
13:30:33 | at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory$anonfun$createEventHandler$6.apply(QueryExecutionEventHandlerFactory.scala:43)
13:30:33 | at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory$anonfun$createEventHandler$6.apply(QueryExecutionEventHandlerFactory.scala:42)
13:30:33 | at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory.withErrorHandling(QueryExecutionEventHandlerFactory.scala:55)
13:30:33 | at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory.createEventHandler(QueryExecutionEventHandlerFactory.scala:41)
13:30:33 | at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener$.za$co$absa$spline$harvester$listener$SplineQueryExecutionListener$constructEventHandler(SplineQueryExecutionListener.scala:67)
13:30:33 | at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.<init>(SplineQueryExecutionListener.scala:37)
13:30:33 | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
13:30:33 | at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
13:30:33 | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
13:30:33 | at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
13:30:33 | at org.apache.spark.util.Utils$anonfun$loadExtensions$1.apply(Utils.scala:2691)
13:30:33 | at org.apache.spark.util.Utils$anonfun$loadExtensions$1.apply(Utils.scala:2680)
13:30:33 | at scala.collection.TraversableLike$anonfun$flatMap$1.apply(TraversableLike.scala:241)
13:30:33 | at scala.collection.TraversableLike$anonfun$flatMap$1.apply(TraversableLike.scala:241)
13:30:33 | at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
13:30:33 | at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
13:30:33 | at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
13:30:33 | at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
13:30:33 | at org.apache.spark.util.Utils$.loadExtensions(Utils.scala:2680)
13:30:33 | at org.apache.spark.sql.util.ExecutionListenerManager$anonfun$lessinit$greater$1.apply(QueryExecutionListener.scala:83)
13:30:33 | at org.apache.spark.sql.util.ExecutionListenerManager$anonfun$lessinit$greater$1.apply(QueryExecutionListener.scala:82)
13:30:33 | at scala.Option.foreach(Option.scala:257)
13:30:33 | at org.apache.spark.sql.util.ExecutionListenerManager.<init>(QueryExecutionListener.scala:82)
13:30:33 | at org.apache.spark.sql.internal.BaseSessionStateBuilder$anonfun$listenerManager$2.apply(BaseSessionStateBuilder.scala:270)
13:30:33 | at org.apache.spark.sql.internal.BaseSessionStateBuilder$anonfun$listenerManager$2.apply(BaseSessionStateBuilder.scala:270)
13:30:33 | at scala.Option.getOrElse(Option.scala:121)
13:30:33 | at org.apache.spark.sql.internal.BaseSessionStateBuilder.listenerManager(BaseSessionStateBuilder.scala:269)
13:30:33 | at org.apache.spark.sql.internal.BaseSessionStateBuilder.build(BaseSessionStateBuilder.scala:297)
13:30:33 | at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$instantiateSessionState(SparkSession.scala:1104)
13:30:33 | at org.apache.spark.sql.SparkSession$anonfun$sessionState$2.apply(SparkSession.scala:145)
13:30:33 | at org.apache.spark.sql.SparkSession$anonfun$sessionState$2.apply(SparkSession.scala:144)
13:30:33 | at scala.Option.getOrElse(Option.scala:121)
13:30:33 | at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:144)
13:30:33 | at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:141)
13:30:33 | at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:77)
13:30:33 | at org.apache.spark.sql.SparkSession.internalCreateDataFrame(SparkSession.scala:578)
13:30:33 | at org.apache.spark.sql.SparkSession.createDataFrame(SparkSession.scala:597)
13:30:33 | at org.apache.spark.sql.SparkSession.createDataFrame(SparkSession.scala:352)
13:30:33 | at za.co.absa.sync.watcher.framework.utils.JdbcNativeUtils$.getJdbcNativeDataFrame(JdbcNativeUtils.scala:103)
13:30:33 | at za.co.absa.sync.watcher.framework.reader.TableReaderJdbcNative.getDataFrame(TableReaderJdbcNative.scala:70)
13:30:33 | at za.co.absa.sync.watcher.framework.reader.TableReaderJdbcNative.getData(TableReaderJdbcNative.scala:56)
13:30:33 | at za.co.absa.sync.watcher.framework.job.v2.job.IngestionJob.getSourcingDataFrame(IngestionJob.scala:103)
13:30:33 | at za.co.absa.sync.watcher.framework.job.v2.job.IngestionJob.run(IngestionJob.scala:76)
13:30:33 | at za.co.absa.sync.watcher.framework.runner.task.TaskRunnerBase$anonfun$4.apply(TaskRunnerBase.scala:155)
13:30:33 | at za.co.absa.sync.watcher.framework.runner.task.TaskRunnerBase$anonfun$4.apply(TaskRunnerBase.scala:152)
13:30:33 | at scala.util.Try$.apply(Try.scala:192)
13:30:33 | at za.co.absa.sync.watcher.framework.runner.task.TaskRunnerBase.run(TaskRunnerBase.scala:152)
13:30:33 | at za.co.absa.sync.watcher.framework.runner.task.TaskRunnerParallel$anonfun$runAllTasks$1$anonfun$apply$1.apply(TaskRunnerParallel.scala:43)
13:30:33 | at za.co.absa.sync.watcher.framework.runner.task.TaskRunnerParallel$anonfun$runAllTasks$1$anonfun$apply$1.apply(TaskRunnerParallel.scala:38)
13:30:33 | at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
13:30:33 | at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
13:30:33 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
13:30:33 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13:30:33 | at java.lang.Thread.run(Thread.java:748)
13:30:33 | Caused by: java.net.SocketTimeoutException: connect timed out
13:30:33 | at java.net.PlainSocketImpl.socketConnect(Native Method)
13:30:33 | at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
13:30:33 | at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
13:30:33 | at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
13:30:33 | at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
13:30:33 | at java.net.Socket.connect(Socket.java:589)
13:30:33 | at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
13:30:33 | at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
13:30:33 | at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
13:30:33 | at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
13:30:33 | at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
13:30:33 | at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
13:30:33 | at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
13:30:33 | at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
13:30:33 | at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
13:30:33 | at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
13:30:33 | at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
13:30:33 | at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
13:30:33 | at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
13:30:33 | at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
13:30:33 | at scalaj.http.HttpRequest.scalaj$http$HttpRequest$doConnection(Http.scala:367)
13:30:33 | at scalaj.http.HttpRequest.exec(Http.scala:343)
13:30:33 | at scalaj.http.HttpRequest.asString(Http.scala:491)
13:30:33 | at za.co.absa.spline.harvester.dispatcher.httpdispatcher.rest.RestEndpoint.head(RestEndpoint.scala:33)
13:30:33 | at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher$anonfun$za$co$absa$spline$harvester$dispatcher$HttpLineageDispatcher$getServerHeaders$2.apply(HttpLineageDispatcher.scala:107)
13:30:33 | at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher$anonfun$za$co$absa$spline$harvester$dispatcher$HttpLineageDispatcher$getServerHeaders$2.apply(HttpLineageDispatcher.scala:107)
13:30:33 | at scala.util.Try$.apply(Try.scala:192)
13:30:33 | at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher$.za$co$absa$spline$harvester$dispatcher$HttpLineageDispatcher$getServerHeaders(HttpLineageDispatcher.scala:107)
13:30:33 | ... 71 more
```

**Comment by cerveada** [comment]
@zhukovgreen again this simply mean the agent was not able to connect to the server. So it's server issue or the network between. To fix this, you have to check the server and find out what is wrong there.

**Comment by wajda** [comment]
@abhishekshenoy 
check your timeout settings, and make sure you are using the latest server and the agent versions.
https://github.com/AbsaOSS/spline-spark-agent/blob/release/0.7.8/core/src/main/resources/spline.default.properties#L38
