### ISSUE TITLE
Admin CLI :: 401 not authorized when user password is empty

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#1049]
On the default ArangoDB setup (user `root` with no password) the following command

```shell
java -jar admin-0.7.5.jar db-init arangodb://root@172.22.0.2/test
```
gives this
```
Exception in thread "main" za.co.absa.spline.common.rest.HttpStatusException: ArangoDB response: HTTP/1.1 401 Unauthorized. {"error":true,"errorNum":11,"errorMessage":"not authorized to execute this request","code":401}
	at za.co.absa.spline.common.rest.RESTClientApacheHttpImpl.$anonfun$execHttp$1(RESTClientApacheHttpImpl.scala:93)
	at za.co.absa.spline.common.rest.RESTClientApacheHttpImpl$$Lambda$471/0x0000000000000000.apply(Unknown Source)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.concurrent.Future$$$Lambda$472/0x0000000000000000.apply(Unknown Source)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.Future$$Lambda$437/0x0000000000000000.apply(Unknown Source)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.Promise$$Lambda$429/0x0000000000000000.apply(Unknown Source)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by wajda** [comment]
The problem is that the basic auth token is created with password `null` while the server expect is to be empty string.
