### ISSUE TITLE
Write delta in spark, when spline parses spark lineage, an error is reported？

### ISSUE THREAD

**Issue by JinJiDeJinMu** [AbsaOSS/spline#1176]
![image](https://user-images.githubusercontent.com/33084817/220305798-782a1f93-f9e0-4441-bc96-ca70e3e3f704.png)

submit code

./spark-submit --class com.hs.test
--master spark://jinmudeMacBook-Pro.local:7077
--name test_015
--jars "/Users/jinmu/Downloads/datahub-spark-lineage-0.10.0rc1.jar"
--conf "spark.extraListeners=datahub.spark.DatahubSparkListener"
--conf "spark.datahub.rest.server=http://localhost:8080/"
/Users/jinmu/Downloads/hs/lakehouse/target/hs-lakehouse-1.0-SNAPSHOT.jar

this code

val spark = SparkSession.builder()
.config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
.config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
.appName("test1")
.master("local[*]")
.getOrCreate()

val path = "/Users/jinmu/Downloads/111.csv"

val readerOptions = Map(
  "delimiter" ->",",
  "header" -> "true",
  "encoding" -> "utf-8",
  "escape" -> "\""
)
import spark.implicits._

spark.read.format("csv").options(readerOptions).load(path)
  .write.format("delta").mode("append")
  .save("/Users/jinmu/Downloads/delta/jinmu.db/test33")

who can help me?

**Comment by cerveada** [comment]
Can you post the whole exception? Preferably as a text.

**Comment by JinJiDeJinMu** [comment]
ok


23/02/21 17:43:38 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
23/02/21 17:43:38 INFO SparkContext: Running Spark version 3.1.2
23/02/21 17:43:39 INFO ResourceUtils: ==============================================================
23/02/21 17:43:39 INFO ResourceUtils: No custom resources configured for spark.driver.
23/02/21 17:43:39 INFO ResourceUtils: ==============================================================
23/02/21 17:43:39 INFO SparkContext: Submitted application: test1
23/02/21 17:43:39 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
23/02/21 17:43:39 INFO ResourceProfile: Limiting resource is cpu
23/02/21 17:43:39 INFO ResourceProfileManager: Added ResourceProfile id: 0
23/02/21 17:43:39 INFO SecurityManager: Changing view acls to: jinmu
23/02/21 17:43:39 INFO SecurityManager: Changing modify acls to: jinmu
23/02/21 17:43:39 INFO SecurityManager: Changing view acls groups to: 
23/02/21 17:43:39 INFO SecurityManager: Changing modify acls groups to: 
23/02/21 17:43:39 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(jinmu); groups with view permissions: Set(); users  with modify permissions: Set(jinmu); groups with modify permissions: Set()
23/02/21 17:43:39 INFO Utils: Successfully started service 'sparkDriver' on port 56109.
23/02/21 17:43:39 INFO SparkEnv: Registering MapOutputTracker
23/02/21 17:43:39 INFO SparkEnv: Registering BlockManagerMaster
23/02/21 17:43:39 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
23/02/21 17:43:39 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
23/02/21 17:43:39 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
23/02/21 17:43:39 INFO DiskBlockManager: Created local directory at /private/var/folders/g6/3j6jyxt964x1pk4qk7_b49rw0000gn/T/blockmgr-315a09b6-cd7a-4b15-b807-99473f820d62
23/02/21 17:43:39 INFO MemoryStore: MemoryStore started with capacity 366.3 MiB
23/02/21 17:43:39 INFO SparkEnv: Registering OutputCommitCoordinator
23/02/21 17:43:39 INFO Utils: Successfully started service 'SparkUI' on port 4040.
23/02/21 17:43:39 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://192.168.218.8:4040
23/02/21 17:43:39 INFO SparkContext: Added JAR file:///Users/jinmu/Downloads/spark-3.1-spline-agent-bundle_2.12-1.0.4.jar at spark://192.168.218.8:56109/jars/spark-3.1-spline-agent-bundle_2.12-1.0.4.jar with timestamp 1676972618954
23/02/21 17:43:39 INFO SparkContext: Added JAR file:/Users/jinmu/Downloads/hs/lakehouse/target/hs-lakehouse-1.0-SNAPSHOT.jar at spark://192.168.218.8:56109/jars/hs-lakehouse-1.0-SNAPSHOT.jar with timestamp 1676972618954
23/02/21 17:43:40 INFO Executor: Starting executor ID driver on host 192.168.218.8
23/02/21 17:43:40 INFO Executor: Fetching spark://192.168.218.8:56109/jars/spark-3.1-spline-agent-bundle_2.12-1.0.4.jar with timestamp 1676972618954
23/02/21 17:43:40 INFO TransportClientFactory: Successfully created connection to /192.168.218.8:56109 after 27 ms (0 ms spent in bootstraps)
23/02/21 17:43:40 INFO Utils: Fetching spark://192.168.218.8:56109/jars/spark-3.1-spline-agent-bundle_2.12-1.0.4.jar to /private/var/folders/g6/3j6jyxt964x1pk4qk7_b49rw0000gn/T/spark-15280169-319f-4d7b-8d11-e3261d824b44/userFiles-6b25b9b2-0b90-4e58-86e7-1a527c6b54ba/fetchFileTemp2786412298596410544.tmp
23/02/21 17:43:40 INFO Executor: Adding file:/private/var/folders/g6/3j6jyxt964x1pk4qk7_b49rw0000gn/T/spark-15280169-319f-4d7b-8d11-e3261d824b44/userFiles-6b25b9b2-0b90-4e58-86e7-1a527c6b54ba/spark-3.1-spline-agent-bundle_2.12-1.0.4.jar to class loader
23/02/21 17:43:40 INFO Executor: Fetching spark://192.168.218.8:56109/jars/hs-lakehouse-1.0-SNAPSHOT.jar with timestamp 1676972618954
23/02/21 17:43:40 INFO Utils: Fetching spark://192.168.218.8:56109/jars/hs-lakehouse-1.0-SNAPSHOT.jar to /private/var/folders/g6/3j6jyxt964x1pk4qk7_b49rw0000gn/T/spark-15280169-319f-4d7b-8d11-e3261d824b44/userFiles-6b25b9b2-0b90-4e58-86e7-1a527c6b54ba/fetchFileTemp8602971486436238988.tmp
23/02/21 17:43:40 INFO Executor: Adding file:/private/var/folders/g6/3j6jyxt964x1pk4qk7_b49rw0000gn/T/spark-15280169-319f-4d7b-8d11-e3261d824b44/userFiles-6b25b9b2-0b90-4e58-86e7-1a527c6b54ba/hs-lakehouse-1.0-SNAPSHOT.jar to class loader
23/02/21 17:43:40 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 56111.
23/02/21 17:43:40 INFO NettyBlockTransferService: Server created on 192.168.218.8:56111
23/02/21 17:43:40 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
23/02/21 17:43:40 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 192.168.218.8, 56111, None)
23/02/21 17:43:40 INFO BlockManagerMasterEndpoint: Registering block manager 192.168.218.8:56111 with 366.3 MiB RAM, BlockManagerId(driver, 192.168.218.8, 56111, None)
23/02/21 17:43:40 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 192.168.218.8, 56111, None)
23/02/21 17:43:40 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 192.168.218.8, 56111, None)
23/02/21 17:43:40 INFO SingleEventLogFileWriter: Logging events to file:/Users/jinmu/Downloads/directory/local-1676972619872.inprogress
23/02/21 17:43:40 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/Users/jinmu/Downloads/soft/spark-3.0.3-bin-hadoop2.7/bin/spark-warehouse').
23/02/21 17:43:40 INFO SharedState: Warehouse path is 'file:/Users/jinmu/Downloads/soft/spark-3.0.3-bin-hadoop2.7/bin/spark-warehouse'.
23/02/21 17:43:41 INFO SparkUI: Stopped Spark web UI at http://192.168.218.8:4040
23/02/21 17:43:41 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
23/02/21 17:43:41 INFO MemoryStore: MemoryStore cleared
23/02/21 17:43:41 INFO BlockManager: BlockManager stopped
23/02/21 17:43:41 INFO BlockManagerMaster: BlockManagerMaster stopped
23/02/21 17:43:41 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
23/02/21 17:43:41 INFO SparkContext: Successfully stopped SparkContext
Exception in thread "main" java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.delta.sql.parser.DeltaSqlParser.<init>(DeltaSqlParser.scala:71)
	at io.delta.sql.DeltaSparkSessionExtension.$anonfun$apply$1(DeltaSparkSessionExtension.scala:79)
	at org.apache.spark.sql.SparkSessionExtensions.$anonfun$buildParser$1(SparkSessionExtensions.scala:239)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:49)
	at org.apache.spark.sql.SparkSessionExtensions.buildParser(SparkSessionExtensions.scala:238)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.sqlParser$lzycompute(BaseSessionStateBuilder.scala:124)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.sqlParser(BaseSessionStateBuilder.scala:123)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.build(BaseSessionStateBuilder.scala:341)
	at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$instantiateSessionState(SparkSession.scala:1145)
	at org.apache.spark.sql.SparkSession.$anonfun$sessionState$2(SparkSession.scala:159)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:155)
	at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:152)
	at org.apache.spark.sql.DataFrameReader.<init>(DataFrameReader.scala:997)
	at org.apache.spark.sql.SparkSession.read(SparkSession.scala:658)
	at com.hs.test$.main(test.scala:36)
	at com.hs.test.main(test.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
23/02/21 17:43:41 INFO ShutdownHookManager: Shutdown hook called
23/02/21 17:43:41 INFO ShutdownHookManager: Deleting directory /private/var/folders/g6/3j6jyxt964x1pk4qk7_b49rw0000gn/T/spark-22f428e3-b4f2-41d8-8ff4-684d30e6517f
23/02/21 17:43:41 INFO ShutdownHookManager: Deleting directory /private/var/folders/g6/3j6jyxt964x1pk4qk7_b49rw0000gn/T/spark-15280169-319f-4d7b-8d11-e3261d824b44
