### ISSUE TITLE
Support for Mongo 3.6

### ISSUE THREAD

**Issue by larryxia-ddl** [AbsaOSS/spline#12]
when I try to login the Spline UI, I got the following exception. it seems the generated mongodb query is not well formatted. ( I am used mongodb 3.6)

If you need more information, please let me know. 

Regards

Larry

```
14:27:06.978 [http-bio-8080-exec-8] ERROR za.co.absa.spline.web.logging.ErrorCode$ - ErrorCode(0689c861-2dd9-4196-a2d0-0f499ca74f31)
com.mongodb.MongoCommandException: Command failed with error 9: 'The 'cursor' option is required, except for aggregate with the explain argument' on server 172.
24.136.111:27017. The full response is { "ok" : 0.0, "errmsg" : "The 'cursor' option is required, except for aggregate with the explain argument", "code" : 9, "codeName" : "FailedToParse" }
        at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:115)
        at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:114)
        at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159
        at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
        at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:173)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:215)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:206)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:112)
        at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:227)
        at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:223)
        at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:239)
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:212)
        at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:223)
        at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:65)
        at com.mongodb.Mongo.execute(Mongo.java:772)
        at com.mongodb.Mongo$2.execute(Mongo.java:759)
        at com.mongodb.DBCollection.aggregate(DBCollection.java:1377)
        at com.mongodb.DBCollection.aggregate(DBCollection.java:1308)
        at com.mongodb.DBCollection.aggregate(DBCollection.java:1294)
        at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$za$co$absa$spline$persistence$mongo$MongoDataLineageReader$$selectPersistedDatasets$1.apply(MongoDataLineageReader.scala:187)
        at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$za$co$absa$spline$persistence$mongo$MongoDataLineageReader$$selectPersistedDatasets$1.apply(MongoDataLineageReader.scala:188)
        at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2$$anon$4.block(ExecutionContextImpl.scala:48)
        at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
        at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2.blockOn(ExecutionContextImpl.scala:45)
        at scala.concurrent.package$.blocking(package.scala:123)
        at za.co.absa.spline.persistence.mongo.MongoDataLineageReader.za$co$absa$spline$persistence$mongo$MongoDataLineageReader$$selectPersistedDatasets(MongoDataLineageReader.scala:188)
        at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$list$1.apply(MongoDataLineageReader.scala:170)
        at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$list$1.apply(MongoDataLineageReader.scala:170)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by wajda** [comment]
Hi Larry. We use Mongo 3.4, so it may be 3.6 related bug.
Let me see if I can reproduce it on 3.6.

**Comment by wajda** [comment]
Yes, upgrading Mongo driver to 3.6 fixes it.

**Comment by larryxia-ddl** [comment]
Thanks, I will try with 3.4.

**Comment by larryxia-ddl** [comment]
It works fine with Mongodb 3.4.

**Comment by prasenjeetp** [comment]
@wajda how do you " upgrading Mongo driver to 3.6 fixes it.". Can you give some steps

**Comment by wajda** [comment]
Just update the dependency version in pom.xml
https://github.com/AbsaOSS/spline/pull/13/commits/6c257f3fc7d6705f5c1b081d11fbde4f29877651

**Comment by rpanjabi** [comment]
Hi @wajda , I am new to pentaho and could not able to find pom.xml file. Can you please guide me.
Thanks

**Comment by wajda** [comment]
Hi @rpanjabi,
You don't need any pom.xml file any more - the issue is fixed. Please try the latest Spline release 0.2.6

**Comment by rpanjabi** [comment]
Hi @wajda , I am using enterprise trial edition. What would be the solution with that.
