### ISSUE TITLE
JDBC write operation support

### ISSUE THREAD

**Issue by attempt1** [AbsaOSS/spline#132]
Spline throws an exception when spark Dataset<Row> is saved via jdbc (Java code).

Java line of code used to save from spark to JDBC:

```scala
sql.coalesce(1).write().mode(SaveMode.Append).jdbc(
  "jdbc:sqlserver://xxxxx;authenticationScheme=JavaKerberos;databaseName=XXX;integratedSecurity=true;",
  "TABLE_NAME_2",
  new Properties());
```

The exception throws is:
```
2019-02-21 16:53:11,279 [main][] WARN  o.apache.spark.sql.util.ExecutionListenerManager - Error executing query execution listener
java.lang.RuntimeException: Unexpected root operation: class za.co.absa.spline.model.op.Generic
            at scala.sys.package$.error(package.scala:27)
            at za.co.absa.spline.core.listener.SplineQueryExecutionListener.wasResultIgnored(SplineQueryExecutionListener.scala:66)
            at za.co.absa.spline.core.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:48)
            at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1$$anonfun$apply$mcV$sp$1.apply(QueryExecutionListener.scala:124)
            at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1$$anonfun$apply$mcV$sp$1.apply(QueryExecutionListener.scala:123)
            at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$org$apache$spark$sql$util$ExecutionListenerManager$$withErrorHandling$1.apply(QueryExecutionListener.scala:145)
            at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$org$apache$spark$sql$util$ExecutionListenerManager$$withErrorHandling$1.apply(QueryExecutionListener.scala:143)
            at scala.collection.immutable.List.foreach(List.scala:381)
            at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
            at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
            at org.apache.spark.sql.util.ExecutionListenerManager.org$apache$spark$sql$util$ExecutionListenerManager$$withErrorHandling(QueryExecutionListener.scala:143)
            at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1.apply$mcV$sp(QueryExecutionListener.scala:123)
            at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1.apply(QueryExecutionListener.scala:123)
            at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1.apply(QueryExecutionListener.scala:123)
            at org.apache.spark.sql.util.ExecutionListenerManager.readLock(QueryExecutionListener.scala:156)
            at org.apache.spark.sql.util.ExecutionListenerManager.onSuccess(QueryExecutionListener.scala:122)
            at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:658)
            at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:273)
            at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:267)
            at org.apache.spark.sql.DataFrameWriter.jdbc(DataFrameWriter.scala:501)
            at com.example.SparkJoiner.main(SparkJoiner.java:512)
2019-02-21 16:53:11,286 [main][] INFO  org.spark_project.jetty.server.AbstractConnector - Stopped Spark@63da207f{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
```

**Comment by wajda** [comment]
Spline doesn't support JDBC writes yet. We'll see if it can be added quickly.

**Comment by attempt1** [comment]
Thanks very much Alex.
