### ISSUE TITLE
UI is not working Error "HTTP:404"Resource not found"

### ISSUE THREAD

**Issue by msv123** [AbsaOSS/spline#172]
Steps:
Downloaded Spline we executable jar of version 0.3.6 from https://absaoss.github.io/spline/
and executed below command
java -jar spline-web-0.3.6-exec-war.jar -Dspline.mongodb.url=mongodb://localhost:27017 -Dspline.mongodb.name=test -httpPort=8888 -X
![image](https://user-images.githubusercontent.com/6581789/55214296-47486700-521c-11e9-9911-a6b77d6f7fba.png)

![image](https://user-images.githubusercontent.com/6581789/55214233-0a7c7000-521c-11e9-9c04-8893d4582191.png)

**Comment by wajda** [comment]
@msv123 I just tried the exact same command on my PC and it worked.
Can you share more details, perhaps some error messages in logs, or Mongo setup?
The last line on your screenshot says - __INFO: Pausing ProtocolHandler ["http-bio-8888"]__
There might be some error details above in the logs.

**Comment by msv123** [comment]
@wajda Initally i tried connecting azure mongodb it was throwing below error .'
cmd  java -jar spline-web-0.3.6-exec-war.jar -D"spline.mongodb.url=mongodb://user:password@host:10255" -D"spline.mongodb.name=test" -httpPort=8213
![image](https://user-images.githubusercontent.com/6581789/55303404-9af8c180-5463-11e9-9b4c-075153becf54.png)

Later i tried steup local  mongo am getting HTTP:404 Resource not found
No logs in mongodb

**Comment by wajda** [comment]
Mongo Java driver error message explains it clearly.
__The connection string contains an invalid host__
__The port is not valid, it must be an integer between 0 and 65535__
Please check the MongoDB connection URL format.

**Comment by wajda** [comment]
If you embed a user password into the connection URL that contains a colon or other special characters, you need to escape them according to the common URL encoding rules, like %XX.

**Comment by msv123** [comment]
@wajda Sorry for troubling can u please some example of url encoding in current scenario .I have crosschecked my connection string it doesn't special characters.I am not able to local mongo db .HTTP 404 error in browser

**Comment by wajda** [comment]
If you look at the error message that says "The port 'xxxxxxxxxxxxxxxxxxxxxxxx' is not valid", that long string is what was recognised as a port number. Try to figure put why. I cannot see it as you crossed it out.

**Comment by msv123** [comment]
This is my actual command java -jar spline-web-0.3.6-exec-war.jar -D"spline.mongodb.url=mongodb://centralmeta:KCrA8vfSCJWHFE0sf5YZJAZagYUovjZ5X099rdDrCxvLpFLYzKQm0ho1c3biTHedfN54A0OolavfuGCfSQA==@centralmeta.documents.azure.com:10255" -D"spline.mongodb.name=test" -httpPort=8213

**Comment by wajda** [comment]
`=` is a reserved character and needs to be encoded (`%3D`)
https://tools.ietf.org/html/rfc3986#section-2.2

**Comment by msv123** [comment]
@wajda Thanks .I am trying to azure cosmos db still i am not able to connect.Can u say how to give values
"SSL=true" & replicaset=globaldb in jar arguments
this my connectionstring for mongodb 
mongodb://centralmeta:KCrA8vfSCJWHFR5YZJAZagYUovjZ5X099rdDrCxvLpFLYzKQm0ho1c3biTHUbwdN54A0OolavfuGCfSQA==@cenlmeta.documents.azure.com:10255/?ssl=true&replicaSet=globaldb
when i am trying to give same in spline mongo url it say not found value ssl

**Comment by wajda** [comment]
Try this:
`mongodb://centralmeta:KCrA8vfSCJWHFR5YZJAZagYUovjZ5X099rdDrCxvLpFLYzKQm0ho1c3biTHUbwdN54A0OolavfuGCfSQA%3D%3D@cenlmeta.documents.azure.com:10255/?ssl=true&replicaSet=globaldb`

**Comment by msv123** [comment]
I tried the same:
Below is error:SEVERE: Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lineageReader' defined in za.co.absa.spline.web.LineageWebAppConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [za.co.absa.spline.persistence.api.DataLineageReader]: Factory method 'lineageReader' threw exception; nested exception is java.lang.IllegalArgumentException: The connection string contains an invalid option 'ssl'. 'ssl' is missing the value delimiter eg 'ssl=value'
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:587)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1250)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:758)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:409)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4797)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5291)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by msv123** [comment]
Ok will check deploying war file to tomcat server.
