### ISSUE TITLE
Exec-jar fails on MongoDB connection URL containing '=' 

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#184]
JVM arguments with the `=` character in a value don't seem to be passed correctly to the embedded Tomcat server and/or Spline application.

```
java -jar spline-web-0.3.6-exec-war.jar -Dspline.mongodb.url=mongodb://localhost:27017/test?ssl=true
```

Throws:

```
Caused by: java.lang.IllegalArgumentException: The connection string contains an invalid option 'ssl'. 'ssl' is missing the value delimiter eg 'ssl=value'
	at com.mongodb.ConnectionString.parseOptions(ConnectionString.java:690)
	at com.mongodb.ConnectionString.<init>(ConnectionString.java:351)
	at com.mongodb.MongoClientURI.<init>(MongoClientURI.java:234)
	at com.mongodb.MongoClientURI.<init>(MongoClientURI.java:216)
	at com.mongodb.casbah.MongoClientURI$.apply(MongoClientURI.scala:47)
	at za.co.absa.spline.persistence.mongo.MongoConnectionImpl.<init>(MongoConnection.scala:36)
	at za.co.absa.spline.web.LineageWebAppConfig.lineageReader(LineageWebAppConfig.scala:55)
	at za.co.absa.spline.web.LineageWebAppConfig$$EnhancerBySpringCGLIB$$2a1a8d18.CGLIB$lineageReader$4(<generated>)
	at za.co.absa.spline.web.LineageWebAppConfig$$EnhancerBySpringCGLIB$$2a1a8d18$$FastClassBySpringCGLIB$$d6d4d204.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
	at za.co.absa.spline.web.LineageWebAppConfig$$EnhancerBySpringCGLIB$$2a1a8d18.lineageReader(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
```

**Comment by msv123** [comment]
Hi @wajda 
Any update on this when this will be fixed

**Comment by wajda** [comment]
This seems to be a bug in Maven Tomcat plugin.
Try using a `.war` file instead of exec-war.jar`, it should work fine.

As for the containerisation solution we are moving towards Docker support that is aimed for Spline 0.4

**Comment by wajda** [comment]
Superseded by #249
