### ISSUE TITLE
Getting Spline working in Docker Jupyter

### ISSUE THREAD

**Issue by boje** [AbsaOSS/spline#211]
My first goal was to make Spline work with [Jupyter](https://github.com/jupyter/docker-stacks/tree/master/all-spark-notebook) in a Docker. I tried to add a downloaded [jar](https://mvnrepository.com/artifact/za.co.absa.spline/spline-core/0.3.7) but with out any luck.

```
jovyan@fe09f61bd9ae:~$ $SPARK_HOME/bin/pyspark --jars /home/jovyan/work/spline-core-0.3.6.jar
Python 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 23:01:00) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
19/04/30 14:25:49 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
19/04/30 14:25:51 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
19/04/30 14:25:51 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.4.1
      /_/

Using Python version 3.7.3 (default, Mar 27 2019 23:01:00)
SparkSession available as 'spark'.
>>> sc._jvm.za.co.absa.spline.core\
... .SparkLineageInitializer.enableLineageTracking(spark._jsparkSession)
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1159, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 985, in send_command
    response = connection.send_command(command)
  File "/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1164, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1487, in __getattr__
py4j.protocol.Py4JError: za.co.absa.spline.core.SparkLineageInitializer.enableLineageTracking does not exist in the JVM
>>> Exception in thread "Thread-5" java.lang.NoClassDefFoundError: org/slf4s/Logger
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:284)
	at py4j.commands.ReflectionCommand.getMember(ReflectionCommand.java:140)
	at py4j.commands.ReflectionCommand.execute(ReflectionCommand.java:91)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.slf4s.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more

Traceback (most recent call last):
```

Next I tried to install Maven and build the sample from [this](https://github.com/AbsaOSS/spline/blob/release/0.3/sample/src/main/scala/za/co/absa/spline/sample/batch/python_sample.py) guide build get a build error.

```
root@e6826435639c:/tmp# git clone https://github.com/AbsaOSS/spline.git
Cloning into 'spline'...
remote: Enumerating objects: 303, done.
remote: Counting objects: 100% (303/303), done.
remote: Compressing objects: 100% (168/168), done.
remote: Total 19002 (delta 124), reused 212 (delta 75), pack-reused 18699
Receiving objects: 100% (19002/19002), 3.65 MiB | 2.83 MiB/s, done.
Resolving deltas: 100% (7290/7290), done.
root@e6826435639c:/tmp# cd 
.empty/                hsperfdata_root/       npm-260-d708c0a0/      npm-338-0fd618d0/      v8-compile-cache-1000/
hsperfdata_jovyan/     mesos.key              npm-313-4f7c125e/      spline/                
root@e6826435639c:/tmp# cd 
.empty/                hsperfdata_root/       npm-260-d708c0a0/      npm-338-0fd618d0/      v8-compile-cache-1000/
hsperfdata_jovyan/     mesos.key              npm-313-4f7c125e/      spline/                
root@e6826435639c:/tmp# cd spline/sample/
root@e6826435639c:/tmp/spline/sample# mvn package -P spark-2.3,shade
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< za.co.absa.spline:spline-sample >-------------------
[INFO] Building spline-sample 0.4.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/scalatest/scalatest-maven-plugin/2.0.0/scalatest-maven-plugin-2.0.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/scalatest/scalatest-maven-plugin/2.0.0/scalatest-maven-plugin-2.0.0.pom (9.6 kB at 10 kB/s)

....


Downloaded from central: https://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.11/3.0.5/scalatest_2.11-3.0.5.jar (10 MB at 303 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:40 min
[INFO] Finished at: 2019-04-30T15:08:43Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project spline-sample: Could not resolve dependencies for project za.co.absa.spline:spline-sample:jar:0.4.0-SNAPSHOT: The following artifacts could not be resolved: za.co.absa.spline:spline-harvester:jar:0.4.0-SNAPSHOT, za.co.absa.spline:spline-linker:jar:0.4.0-SNAPSHOT, za.co.absa.spline:spline-spark-adapter-2.3:jar:0.4.0-SNAPSHOT, za.co.absa.spline:spline-persistence-mongo:jar:0.4.0-SNAPSHOT, za.co.absa.spline:spline-persistence-hdfs:jar:0.4.0-SNAPSHOT, za.co.absa.spline:spline-persistence-atlas:jar:0.4.0-SNAPSHOT: Could not find artifact za.co.absa.spline:spline-harvester:jar:0.4.0-SNAPSHOT in java-velocypack-module-scala-mvn-repo (https://raw.github.com/wajda/java-velocypack-module-scala/mvn-repo/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```
Question:

1. If Jars just can be downloaded and add like `$SPARK_HOME/bin/pyspark --jars /home/jovyan/work/spline-core-0.3.6.jar` where can I download the Jars and which one do I need?
2. If I need to build the Jar from strach, how can I then overcome the error above?

**Comment by lukasnalezenec** [comment]
Hi,
Try this one:
https://mvnrepository.com/artifact/za.co.absa.spline/spline-bundle-2_4
Lukas

út 30. 4. 2019 v 17:26 odesílatel Anders Boje Larsen <
notifications@github.com> napsal:

**Comment by boje** [comment]
Thanks that help.
I know have a Jupyter Notebook and Spline UI running in one docker container and a MongoDB running in another docker container.
Everything that is needed is this:

**Start Jupyter Docker with Spark (Scala and PySpark)**
docker run -p 8888:8888 -p 8082:8080 -e GRANT_SUDO=yes --user root -v "$PWD/examples":/home/jovyan/work jupyter/all-spark-notebook

**and run this notebook in your Jupyter container**
[https://www.dropbox.com/s/v30zj1p6kc5e3a9/Spline_test_of_spark_data_lineage.ipynb?dl=0](https://www.dropbox.com/s/v30zj1p6kc5e3a9/Spline_test_of_spark_data_lineage.ipynb?dl=0)
