### ISSUE TITLE
exception "PersistedDatasetDescriptor requires value for 'path'" viewing lineage

### ISSUE THREAD

**Issue by cvaliente** [AbsaOSS/spline#213]
same issue as https://github.com/AbsaOSS/spline/issues/169 which is closed already.

I have a simple spark job that reliably crashes the lineage UI with the stacktrace 
```
13:04:18.675 [http-bio-20710-exec-4] ERROR za.co.absa.spline.web.logging.ErrorCode$ - ErrorCode(00d68101-032a-4215-a30c-3a1528c53cad)
java.lang.RuntimeException: class za.co.absa.spline.model.PersistedDatasetDescriptor requires value for 'path'
	at scala.sys.package$.error(package.scala:27)
	at salat.DefaultArg.safeValue$lzycompute(Grater.scala:484)
	at salat.DefaultArg.safeValue(Grater.scala:480)
	at salat.ConcreteGrater.safeDefault(Grater.scala:435)
	at salat.ConcreteGrater$$anonfun$7$$anonfun$apply$3.apply(Grater.scala:322)
	at salat.ConcreteGrater$$anonfun$7$$anonfun$apply$3.apply(Grater.scala:322)
	at scala.Option.orElse(Option.scala:289)
	at salat.ConcreteGrater$$anonfun$7.apply(Grater.scala:322)
	at salat.ConcreteGrater$$anonfun$7.apply(Grater.scala:307)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at salat.ConcreteGrater.asObject(Grater.scala:307)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$findDatasets$1$$anonfun$apply$5.apply(MongoDataLineageReader.scala:80)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$findDatasets$1$$anonfun$apply$5.apply(MongoDataLineageReader.scala:79)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$class.toStream(Iterator.scala:1320)
	at scala.collection.AbstractIterator.toStream(Iterator.scala:1334)
	at za.co.absa.spline.web.json.StringJSONConverters$CloseableIterableToJson$$anonfun$asJsonArrayInto$2.apply(StringJSONConverters.scala:89)
	at za.co.absa.spline.web.json.StringJSONConverters$CloseableIterableToJson$$anonfun$asJsonArrayInto$2.apply(StringJSONConverters.scala:89)
	at za.co.absa.spline.common.ARM$.using(ARM.scala:31)
	at za.co.absa.spline.web.json.StringJSONConverters$CloseableIterableToJson.asJsonArrayInto(StringJSONConverters.scala:89)
	at za.co.absa.spline.web.rest.controller.LineageController$$anonfun$datasetDescriptors$1.apply(LineageController.scala:63)
	at za.co.absa.spline.web.rest.controller.LineageController$$anonfun$datasetDescriptors$1.apply(LineageController.scala:63)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

The job is simply inserting an unpartitioned table as a partition into a partitioned table (same schema, with the exception of an additional 'ymd' partition column of datatype int).
```
spark
      .table("cvaliente.path")
      .withColumn("ymd", lit(20190401))
      .write
      .mode(SaveMode.Overwrite)
      .insertInto("cvaliente.path_archive")
```
Writing the same table (cvaliente.path) to another unpartitioned table of the same schema works fine.

find attached the log output from the spark application and a dump of the mongo db.
[spline-db-dump.zip](https://github.com/AbsaOSS/spline/files/3138148/spline-db-dump.zip)
[spark_application.log](https://github.com/AbsaOSS/spline/files/3138150/spark_application.log)

**Comment by wajda** [comment]
Thank you @cvaliente,
now we see the problem, just need to find a solution.

The problem is that in you case the `insertInto` wasn't recognized as a write operation.

```json
{"_id":{"$binary":"xEEsnnzhSDTPfusdLU4MsQ==","$type":"03"},"_t":{"$binary":"BQl0b0IxCTvvptyUiERlCNaru4xtEU6B0UM=","$type":"00"},"mainProps":{"_id":{"$binary":"xEEsnnzhSDTPfusdLU4MsQ==","$type":"03"},"name":"InsertIntoHiveTable","inputs":[{"$binary":"Ak0jY5oYwIE+e4uKWbTllw==","$type":"03"}],"output":{"$binary":"7EFKWCBqC0M12TTqc5Wjkw==","$type":"03"}},"rawString":"InsertIntoHiveTable `cvaliente`.`path_archive`, org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe, Map(ymd -\u003e None), true, false, [key, parent_path_id, geo_path_id, category_id, category_type, level, is_empty, is_geographic, is_primary, is_multi_search_path, path_id_1, path_id_2, path_id_3, path_id_4, path_id_5, path_id_6, path_id_7, path_id_8, path_id_9, path_id_10, count_hotel, count_visible_hotel, count_attraction, count_image, ... 11 more fields]","_lineageId":"ln_430b6a20-584a-41ec-93a3-9573ea34d935","_index":0}
```
