### ISSUE TITLE
spline 0.3.8 still throwing exception "PersistedDatasetDescriptor requires value for 'path'" viewing lineage

### ISSUE THREAD

**Issue by cvaliente** [AbsaOSS/spline#246]
unfortunately the issue in #213 still exists with spline 0.3.8

`java.lang.RuntimeException: class za.co.absa.spline.model.PersistedDatasetDescriptor requires value for 'path'
	at scala.sys.package$.error(package.scala:27)
	at salat.DefaultArg.safeValue$lzycompute(Grater.scala:484)
	at salat.DefaultArg.safeValue(Grater.scala:480)
	at salat.ConcreteGrater.safeDefault(Grater.scala:435)
	at salat.ConcreteGrater$$anonfun$7$$anonfun$apply$3.apply(Grater.scala:322)
	at salat.ConcreteGrater$$anonfun$7$$anonfun$apply$3.apply(Grater.scala:322)
	at scala.Option.orElse(Option.scala:289)
	at salat.ConcreteGrater$$anonfun$7.apply(Grater.scala:322)
	at salat.ConcreteGrater$$anonfun$7.apply(Grater.scala:307)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at salat.ConcreteGrater.asObject(Grater.scala:307)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$findDatasets$1$$anonfun$apply$5.apply(MongoDataLineageReader.scala:80)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$findDatasets$1$$anonfun$apply$5.apply(MongoDataLineageReader.scala:79)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$class.toStream(Iterator.scala:1320)
	at scala.collection.AbstractIterator.toStream(Iterator.scala:1334)
	at za.co.absa.spline.web.json.StringJSONConverters$CloseableIterableToJson$$anonfun$asJsonArrayInto$2.apply(StringJSONConverters.scala:89)
	at za.co.absa.spline.web.json.StringJSONConverters$CloseableIterableToJson$$anonfun$asJsonArrayInto$2.apply(StringJSONConverters.scala:89)
	at za.co.absa.spline.common.ARM$.using(ARM.scala:31)
	at za.co.absa.spline.web.json.StringJSONConverters$CloseableIterableToJson.asJsonArrayInto(StringJSONConverters.scala:89)
	at za.co.absa.spline.web.rest.controller.LineageController$$anonfun$datasetDescriptors$1.apply(LineageController.scala:63)
	at za.co.absa.spline.web.rest.controller.LineageController$$anonfun$datasetDescriptors$1.apply(LineageController.scala:63)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
`
it's the same test application as in #213 
I attached the log of the spark application as well as the mongo db dump.
it's a fresh dataset generated on an empty db using spline 0.3.8

[spark-application.log](https://github.com/AbsaOSS/spline/files/3215891/spark-application.log)
[spline-db-dump.zip](https://github.com/AbsaOSS/spline/files/3215892/spline-db-dump.zip)

**Comment by lukasnalezenec** [comment]
Hi, can you make unit test script that will reproduce the issue from start to end for us ?

**Comment by cvaliente** [comment]
@lukasnalezenec 
you can use the unit test from #235 
The unit test works if the table is created in spark. But it fails if the table was created in Hive first, with the stacktrace above.

in hive:
```
CREATE TABLE cvaliente.spline_path_archive (x String) PARTITIONED BY (ymd int) Stored as parquet;
INSERT INTO cvaliente.spline_path_archive PARTITION (ymd = 20190401) VALUES ('Tata');
INSERT INTO cvaliente.spline_path_archive PARTITION (ymd = 20190403) VALUES ('Tere');
CREATE TABLE cvaliente.spline_path (x String) Stored as parquet;
INSERT INTO cvaliente.spline_path VALUES ('Monika');
INSERT INTO cvaliente.spline_path VALUES ('Buba');
```

then, in spark:
```
spark
      .table("cvaliente.spline_path")
      .withColumn("ymd", lit(20190501))
      .write.mode(SaveMode.Overwrite).insertInto("cvaliente.spline_path_archive")
```

I don't know why it makes a difference whether the table was created by hive or spark. Probably related to the tblproperties that spark usually sets?

**Comment by algattik** [comment]
In addition, the REST exception handler seems to be broken, the original exception is swallowed and this gets logged instead (at least in the context of #263):

```
Jun 02, 2019 1:51:21 PM org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver doResolveHandlerMethodException
WARNING: Failed to invoke @ExceptionHandler method: public org.springframework.http.ResponseEntity<java.lang.String> za.co.absa.spline.web.rest.controller.RESTErrorControllerAdvice.handle_500(java.lang.Throwable)
java.lang.IllegalStateException: getWriter() has already been called for this response
	at org.apache.catalina.connector.Response.getOutputStream(Response.java:644)
	at org.apache.catalina.connector.ResponseFacade.getOutputStream(ResponseFacade.java:196)
```

**Comment by wajda** [comment]
@cvaliente, @algattik 
Can you please confirm that it's fixed?

**Comment by cvaliente** [comment]
@wajda it works for me now, using spline 0.3.9

Thanks a lot!

**Comment by gaurangshah9** [comment]
@wajda  I am still getting this error with **spline-bundle-2_4-0.3.9.jar**.  I am using `Delta Table` With `Azure DataBricks`.  I have opened the following issue #321
