### ISSUE TITLE
Atlas integration: to be or not to be

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#279]
We need to decide how Spline in its new concept is related to Apache Atlas. Whether we should leverage Atlas or compete with it. And then we'll decide how do we go about Atlas integration.

Related:
#92 
#75 
#36

**Comment by SouravMalliK** [comment]
Hi,
We are getting this error after placing spline-meta-model.json in atlas 1.0 in HDP 3.1. Can you please help us out to debug the issue --

`2019-07-25 11:25:22,253 ERROR - [main:] ~ AtlasType.fromJson() (AtlasJson:131)
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (StringReader); line: 7, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:669)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:567)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1892)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:747)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4129)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3988)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
        at org.apache.atlas.utils.AtlasJson.fromJson(AtlasJson.java:125)
        at org.apache.atlas.type.AtlasType.fromJson(AtlasType.java:139)
        at org.apache.atlas.repository.store.bootstrap.AtlasTypeDefStoreInitializer.loadModelsInFolder(AtlasTypeDefStoreInitializer.java:169)
        at org.apache.atlas.repository.store.bootstrap.AtlasTypeDefStoreInitializer.loadBootstrapTypeDefs(AtlasTypeDefStoreInitializer.java:137)
        at org.apache.atlas.repository.store.bootstrap.AtlasTypeDefStoreInitializer.init(AtlasTypeDefStoreInitializer.java:94)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:297)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.apache.atlas.web.setup.KerberosAwareListener.contextInitialized(KerberosAwareListener.java:31)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:843)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:816)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:422)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:389)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.apache.atlas.web.service.EmbeddedServer.start(EmbeddedServer.java:98)
        at org.apache.atlas.Atlas.main(Atlas.java:133)
2019-07-25 11:25:22,255 INFO  - [main:] ~ No type in file /usr/hdp/3.1.0.0-78/atlas/models/1000-Hadoop/1090-spline-meta_model.json (AtlasTypeDefStoreInitializer:172)
`

**Comment by wajda** [comment]
This ticket is about removing or re-introducing Atlas support in future versions of Spline.
I'll move your bug report to a new ticket.

**Comment by iamgzy** [comment]
Hi @wajda & Spline team

Thank you for referencing my ticket to this topic, actually I'd love to share some advice on Atlas Integration -- **Please keep the support on Atlas integration.**

I am working on a major company with big data platform to handle many ETL transactions daily/monthly/quarterly. As developer involved in data lineage solution, I like Spline a lot and promote it constantly as it is a better tool to fill in lineage for Spark that Spark-Atlas-Connector can't even compete. That being said, please allow me to share a few facts that the inclusion of Atlas support may help the prosperity of Spline in the industry

1. Atlas is part of HDP/CDP and it is meant for data lineage/governance across various components within the Hadoop ecosystem. Atlas support means Spark lineage data can be part of the data flow visible across the whole eco system. If peeling Atlas support from Spline then it becomes just an additional Utility just for Spark, instead of part of HDP system so that end user has to logon Atlas for find something for Sqoop, Hive etc, Spline UI for just Spark. 
2. Big companies tend to be conservative on integration/update technology, esp on utility level tools like Spline. There is quite push-back while I tried to push for Spline for acceptance. A common question would be "How's your recommendation compatible to our existing platform", "how about security concern if spline lineage data stored in separate meta store", big companies tend to stay on popular platforms like Hadoop, MS/Oracle. Without Atlas integration it just diminish the compatibility/usability of Spline to be used in existing hadoop system.

**Comment by wajda** [comment]
Hi @iamgzy,
Thank you for your really valuable input. We will definitely take it into consideration.

I agree with everything you said. Actually those are the points on the _Pros_ side. There are also _Cons_ however. First and foremost is development cost. Spline is being rewritten with much more broad concept in mind. We are trying to make it not only for Spark but rather a general purpose data lineage tracking and monitoring tool. Existing Atlas persister is incompatible with the new architecture and has to be rewritten. It means that we need to dedicate some dev resources to it. Unfortunately we lack of those. There are plenty of other higher priority issues for us to solve.

Another important aspect to consider is the role of Spline in HDP/CDP. I totally agree that Spline could be a good addition to Atlas, but in out new vision Spline is seen as a central lineage tracking tool, not Atlas. Even though we still have miles in front of us to start actually competing with Atlas, but we are moving in that direction. Spline and Atlas have many overlaps in purpose, but approach some problems differently. While Atlas is more generic tool, Spline goes deeper into lineage details, collects and stores more aspects of the data flows, and aims to provide more insight on things. Spline has to maintain its own database, and for an organization to benefit from all those features that Spline can provide it's necessary to integrate with Spline directly. Without having the lineage data sent directly from the source system Spline will hardly be able to create a complete picture. So, from this perspective having Spline fully integrated with all HDP/CDP components the Atlas's role is questioned.

P.S.
while writing this comment another idea came to my mind. To provide Atlas support without diminishing the role of Spline as a central lineage tracking component) we could extract the Spark lineage harvesting component from Spline into a separate project, and use it as both a Spark-Atlas connector and Spark-Spline connector. That actually sounds feasible. And with that we could kill two birds with one stone.

**Comment by kaustubhghode** [comment]
What exactly are the steps required to Integrate Spline with Atlas(present on Cluster and not on virtual sandbox)? can you please guide me with the steps in detail.

**Comment by iamgzy** [comment]
@kaustubhghode Have you successfully deployed Spline with MongoDB and also have a running Atlas instance in the Hadoop environment? If so then just make a little change in `spline.properties` from your application

> spline.persistence.factory=za.co.absa.spline.persistence.atlas.AtlasPersistenceFactory
>atlas.kafka.bootstrap.servers=_hadoop_ip_:6667
>atlas.kafka.hook.group.id=_atlas_group_id
>atlas.kafka.zookeeper.connect=_hadoop_ip_:2181

Above are settings used in Spline 0.3.9
The _abc_ above is placeholder, please fill in corresponding value from your cluster environment.

**Comment by kaustubhghode** [comment]
@iamgzy 
Thanks for the help.It works fine and I am able to see the Spark -lineage on Atlas.
just out of curiosity what is the need of kafka here,why we have set "atlas.kafka.bootstrap.servers=hadoop_ip:6667
atlas.kafka.hook.group.id=atlas_group_id
atlas.kafka.zookeeper.connect=hadoop_ip:2181 " in the spline.properties

**Comment by boje** [comment]
Apache Atlas is not only used by Cloudera/Hortonworks but many other small and global vendors. The used of Spline together with other Data Governance tools which also support other programming/ETL tools is where I think most will find it useful.
If Spline don't support the integration in the future, I would need to replace it with the Hortonworks Spark Atlas connector.

**Comment by naveen09** [comment]
Guys we are really on it, please do merge with master so that it indirectly helps lot of companies around. Spline is a great library and we see a lot from it, SAC is not even near. We are one among many who are waiting to merge spline branch with master.

**Comment by wajda** [comment]
It's been a long time since we started this discussion and lots of things has changed and clarified since then.

Atlas integration used to be supported as a plug-in embedded into the Spline 0.3.x version series.
Starting from Spline 0.4 the Atlas support has been dropped. The main reason for this was that the Spline vision and internal model began to grow, and Atlas integration just didn't fit anymore. Both Atlas and Spline overlap and conflict in their roles in the enterprise data ecosystem, specifically in what relates to the data lineage tracking. What Spline and Atlas are different in however is the way how they approach the aforementioned problem, so there is no seamless integration from our perspective.

We considered several options how we can go about Atlas integration, and the best possible option so far appears to be the following - **we let the community to develop a Spline-Atlas adapter**.

Starting with Spline 0.5 the Spark agent project resides in its own [repo](https://github.com/AbsaOSS/spline-spark-agent) and is communicating with Spline using a REST API. It also has a pluggable interface that allows you to attach a custom lineage handler, so if all you want is to send the lineage info to Atlas or any other custom system, other than using a full-featured Spline server, you can easily achieve it with just an agent itself. See the example in the comment - https://github.com/AbsaOSS/spline-spark-agent/issues/35#issuecomment-597789962

So it would be awesome if somebody from the community starts a new project and develop a simple JAR that would do a similar business as the [AtlasPersistingFactory](https://github.com/AbsaOSS/spline/blob/release/0.3.9/persistence/atlas/src/main/scala/za/co/absa/spline/persistence/atlas/AtlasPersistenceFactory.scala) from the Spline 0.3 series, but just using a different input model. And simply use that JAR together with Spline Agent as an adapter.

From the perspective of Spline server we don't see how we can leverage Atlas (for now). Of course this could change in the future, for that will be a different story.

So I thing the issue can be closed.
