### ISSUE TITLE
spline does not show lineage if target is table 

### ISSUE THREAD

**Issue by gaurangshah9** [AbsaOSS/spline#321]
Hi Guys, 

I am trying to use spline with Azure Databricks with Comos DB.  If I run the query where it reads from either table/view/file and writes to another file. it shows me the lineage.  However, if I read from table/view/file and write to table it doesn't report any lineage. 

**Sample Tables**

```
%sql 
drop table if exists sourceTable;
create table sourceTable (id int, name string) 
USING delta;
create table targetTable (id int, name string) 
using delta;
```

**Populate Data**

```
%scala 
val df = Seq(
  (1, "AA"),
  (2, "BB"),
  (3, "CC"),
  (4, "DD")
  
).toDF("id", "name")
df.write.mode(SaveMode.Overwrite).insertInto("sourceTable")
```

**If I write to table, it does not report any lineage.** 

```%sql
val df = spark.sql(s"select * from sourceTable where id > 1")
df.write.mode(SaveMode.Overwrite).insertInto("targetTable")
```

**If I write to CSV file it does.** 

```
%sql
val df = spark.sql(s"select * from sourceTable where id > 1")
df.write.mode(SaveMode.Overwrite).csv("/tmp/targetTable1")
```

**With Latest Uber JAR. It shows data being reported in CosmosDB, however when I run webui it shows following stacktrace.** 

**JAR:**  spline-bundle-2_4-0.3.9.jar

```
Aug 20, 2019 1:18:21 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [rest_dispatcher] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: class za.co.absa.spline.model.PersistedDatasetDescriptor requires value for 'path'] with root cause
java.lang.RuntimeException: class za.co.absa.spline.model.PersistedDatasetDescriptor requires value for 'path'
	at scala.sys.package$.error(package.scala:27)
	at salat.DefaultArg.safeValue$lzycompute(Grater.scala:484)
	at salat.DefaultArg.safeValue(Grater.scala:480)
	at salat.ConcreteGrater.safeDefault(Grater.scala:435)
	at salat.ConcreteGrater$$anonfun$7$$anonfun$apply$3.apply(Grater.scala:322)
	at salat.ConcreteGrater$$anonfun$7$$anonfun$apply$3.apply(Grater.scala:322)
	at scala.Option.orElse(Option.scala:289)
	at salat.ConcreteGrater$$anonfun$7.apply(Grater.scala:322)
	at salat.ConcreteGrater$$anonfun$7.apply(Grater.scala:307)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at salat.ConcreteGrater.asObject(Grater.scala:307)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$findDatasets$1$$anonfun$apply$5.apply(MongoDataLineageReader.scala:80)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageReader$$anonfun$findDatasets$1$$anonfun$apply$5.apply(MongoDataLineageReader.scala:79)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$class.toStream(Iterator.scala:1320)
	at scala.collection.AbstractIterator.toStream(Iterator.scala:1334)
	at scala.collection.Iterator$$anonfun$toStream$1.apply(Iterator.scala:1320)
	at scala.collection.Iterator$$anonfun$toStream$1.apply(Iterator.scala:1320)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1233)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1223)
	at scala.collection.immutable.StreamIterator$$anonfun$next$1.apply(Stream.scala:1120)
	at scala.collection.immutable.StreamIterator$$anonfun$next$1.apply(Stream.scala:1120)
	at scala.collection.immutable.StreamIterator$LazyCell.v$lzycompute(Stream.scala:1109)
	at scala.collection.immutable.StreamIterator$LazyCell.v(Stream.scala:1109)
	at scala.collection.immutable.StreamIterator.hasNext(Stream.scala:1114)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:157)
	at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:67)
	at org.json4s.native.Serialization$.write(Serialization.scala:43)
	at za.co.absa.spline.web.json.StringJSONConverters$CloseableIterableToJson$$anonfun$asJsonArrayInto$2.apply(StringJSONConverters.scala:89)
	at za.co.absa.spline.web.json.StringJSONConverters$CloseableIterableToJson$$anonfun$asJsonArrayInto$2.apply(StringJSONConverters.scala:89)
	at za.co.absa.spline.common.ARM$.using(ARM.scala:31)
	at za.co.absa.spline.web.json.StringJSONConverters$CloseableIterableToJson.asJsonArrayInto(StringJSONConverters.scala:89)
	at za.co.absa.spline.web.rest.controller.LineageController$$anonfun$datasetDescriptors$1.apply(LineageController.scala:63)
	at za.co.absa.spline.web.rest.controller.LineageController$$anonfun$datasetDescriptors$1.apply(LineageController.scala:63)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by wajda** [comment]
Hi @gaurangshah9. Thanks for the report. It seems to be the same issue as #263 
Spline 0.3 is EOL. We will address this and other edge use-cases in Spline 0.4 (that is about to be released) or in one of the following versions that will be released shortly after 0.4
