### ISSUE TITLE
Integerating spline with pyspark for Spark-2.4

### ISSUE THREAD

**Issue by roshnaramesh** [AbsaOSS/spline#388]
I followed https://github.com/AbsaOSS/spline/blob/release/0.3/sample/src/main/scala/za/co/absa/spline/sample/batch/python_sample.py as a tutorial to make my python application spit out lineage information to Mongo.
I'm using Spark 2.4, Scala 2.12 and Pyspark 2.4.3.
I'm getting the following error
```
java.lang.NoClassDefFoundError: scala/tools/scalap/scalax/rules/scalasig/ByteCode$
	at salat.util.ScalaSigUtil$.parseClassFileFromByteCode(ScalaSigUtil.scala:39)
	at salat.util.ScalaSigUtil$.parseScalaSig0(ScalaSigUtil.scala:83)
	at salat.ClassAnalyzer$.findSym(ClassAnalyzer.scala:46)
	at salat.ClassAnalyzer.<init>(ClassAnalyzer.scala:136)
	at salat.ConcreteGrater.ca$lzycompute(Grater.scala:120)
	at salat.ConcreteGrater.ca(Grater.scala:120)
	at salat.ConcreteGrater.useTypeHint$lzycompute(Grater.scala:124)
	at salat.ConcreteGrater.useTypeHint(Grater.scala:123)
	at salat.ConcreteGrater.asDBObject(Grater.scala:291)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageWriter.store(MongoDataLineageWriter.scala:32)
	at za.co.absa.spline.core.SparkLineageProcessor$$anonfun$2.apply(SparkLineageProcessor.scala:50)
	at za.co.absa.spline.core.SparkLineageProcessor$$anonfun$2.apply(SparkLineageProcessor.scala:49)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: scala.tools.scalap.scalax.rules.scalasig.ByteCode$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more
```

I tried doing the same with Spark 2.3 and it worked fine. I wanted to ask if it isn't compatible with this version? Could you please help me out?

**Comment by wajda** [comment]
Hi @roshnaramesh,
Spline 0.3 only supports Scala 2.11.
We are working on a cross-compilation for Scala 2.12 onward.

**Comment by roshnaramesh** [comment]
Hello @wajda. Thanks for your prompt reply. I tried using Scala version 2.11.11 and I got the same error. I'm not sure what else I'm missing.

**Comment by wajda** [comment]
Can you please double check that Scala 2.11 is actually the one that the Spark driver runs on.
If so then try to give us more inputs (logs, exact command line you use etc)

**Comment by roshnaramesh** [comment]
Hello @wajda ,
1.I cloned the following project https://github.com/AbsaOSS/spline/tree/release/0.3/sample and ran the command `mvn package -P spark-2.4,shade`. These are the logs when i build that jar
`
Picked up _JAVA_OPTIONS: -Djavax.net.ssl.trustStore=C:\Windows\Sun\Java\Deployment\trusted.certs
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< za.co.absa.spline:spline-sample >-------------------
[INFO] Building spline-sample 0.3.9
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ spline-sample ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- scala-maven-plugin:3.3.1:add-source (scala-compile) @ spline-sample ---
[INFO] Add Source directory: C:\Users\jh814289\IdeaProjects\spline-source-code\spline\sample\src\main\scala
[INFO] Add Test Source directory: C:\Users\jh814289\IdeaProjects\spline-source-code\spline\sample\src\test\scala
[INFO]
[INFO] --- scala-maven-plugin:3.3.1:compile (scala-compile) @ spline-sample ---
[INFO] C:\Users\jh814289\IdeaProjects\spline-source-code\spline\sample\src\main\scala:-1: info: compiling
[INFO] Compiling 9 source files to C:\Users\jh814289\IdeaProjects\spline-source-code\spline\sample\target\classes at 1571340615664
[INFO] Picked up _JAVA_OPTIONS: -Djavax.net.ssl.trustStore=C:\Windows\Sun\Java\Deployment\trusted.certs
[INFO] prepare-compile in 0 s
[INFO] compile in 32 s
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ spline-sample ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to C:\Users\jh814289\IdeaProjects\spline-source-code\spline\sample\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ spline-sample ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\jh814289\IdeaProjects\spline-source-code\spline\sample\src\test\resources
[INFO]
[INFO] --- scala-maven-plugin:3.3.1:testCompile (scala-test-compile) @ spline-sample ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ spline-sample ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.20.1:test (default-test) @ spline-sample ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- scalatest-maven-plugin:2.0.0:test (test) @ spline-sample ---
Discovery starting.
Discovery completed in 713 milliseconds.
Run starting. Expected test count is: 0
DiscoverySuite:
Run completed in 787 milliseconds.
Total number of tests run: 0
Suites: completed 1, aborted 0
Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
No tests were executed.
Picked up _JAVA_OPTIONS: -Djavax.net.ssl.trustStore=C:\Windows\Sun\Java\Deployment\trusted.certs
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ spline-sample ---
[INFO] Building jar: C:\Users\jh814289\IdeaProjects\spline-source-code\spline\sample\target\spline-sample-0.3.9.jar
[INFO]
[INFO] --- maven-shade-plugin:3.1.0:shade (default) @ spline-sample ---
[INFO] Including org.apache.avro:avro:jar:1.8.2 in the shaded jar.
[INFO] Including org.codehaus.jackson:jackson-core-asl:jar:1.9.13 in the shaded jar.
[INFO] Including org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13 in the shaded jar.
[INFO] Including com.thoughtworks.paranamer:paranamer:jar:2.7 in the shaded jar.
[INFO] Including org.apache.commons:commons-compress:jar:1.8.1 in the shaded jar.
[INFO] Including org.tukaani:xz:jar:1.5 in the shaded jar.
[INFO] Including commons-codec:commons-codec:jar:1.11 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-hdfs:jar:2.6.5 in the shaded jar.
[INFO] Including xerces:xercesImpl:jar:2.9.1 in the shaded jar.
[INFO] Including xml-apis:xml-apis:jar:1.3.04 in the shaded jar.
[INFO] Including javax.xml.bind:jaxb-api:jar:2.2.2 in the shaded jar.
[INFO] Including javax.xml.stream:stax-api:jar:1.0-2 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-annotations:jar:2.6.5 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-core:jar:2.6.7 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-annotations:jar:2.6.7 in the shaded jar.
[INFO] Including javax.activation:activation:jar:1.1.1 in the shaded jar.
[INFO] Including org.apache.curator:curator-recipes:jar:2.6.0 in the shaded jar.
[INFO] Including org.apache.curator:curator-framework:jar:2.6.0 in the shaded jar.
[INFO] Including com.google.guava:guava:jar:16.0.1 in the shaded jar.
[INFO] Including org.apache.zookeeper:zookeeper:jar:3.4.6 in the shaded jar.
[INFO] Including org.apache.commons:commons-lang3:jar:3.5 in the shaded jar.
[INFO] Including org.apache.commons:commons-math3:jar:3.4.1 in the shaded jar.
[INFO] Including com.google.code.findbugs:jsr305:jar:1.3.9 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.25 in the shaded jar.
[INFO] Including org.slf4j:jul-to-slf4j:jar:1.7.25 in the shaded jar.
[INFO] Including log4j:log4j:jar:1.2.17 in the shaded jar.
[INFO] Including org.slf4j:slf4j-log4j12:jar:1.7.25 in the shaded jar.
[INFO] Including org.xerial.snappy:snappy-java:jar:1.1.7.1 in the shaded jar.
[INFO] Including org.lz4:lz4-java:jar:1.4.0 in the shaded jar.
[INFO] Including commons-net:commons-net:jar:3.1 in the shaded jar.
[INFO] Including org.json4s:json4s-core_2.11:jar:3.5.3 in the shaded jar.
[INFO] Including org.json4s:json4s-ast_2.11:jar:3.5.3 in the shaded jar.
[INFO] Including org.json4s:json4s-scalap_2.11:jar:3.5.3 in the shaded jar.
[INFO] Including io.netty:netty:jar:3.9.9.Final in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-databind:jar:2.6.7.1 in the shaded jar.
[INFO] Including com.google.protobuf:protobuf-java:jar:2.5.0 in the shaded jar.
[INFO] Including commons-lang:commons-lang:jar:2.6 in the shaded jar.
[INFO] Including joda-time:joda-time:jar:2.9.9 in the shaded jar.
[INFO] Including za.co.absa.spline:spline-core:jar:0.3.9 in the shaded jar.
[INFO] Including za.co.absa.spline:spline-core-spark-adapter-api:jar:0.3.9 in the shaded jar.
[INFO] Including za.co.absa.spline:spline-commons:jar:0.3.9 in the shaded jar.
[INFO] Including za.co.absa.spline:spline-model:jar:0.3.9 in the shaded jar.
[INFO] Including com.github.salat:salat-util_2.11:jar:1.11.2 in the shaded jar.
[INFO] Including za.co.absa.spline:spline-persistence-api:jar:0.3.9 in the shaded jar.
[INFO] Including org.slf4s:slf4s-api_2.11:jar:1.7.25 in the shaded jar.
[INFO] Including commons-configuration:commons-configuration:jar:1.10 in the shaded jar.
[INFO] Including org.scalaz:scalaz-core_2.11:jar:7.2.27 in the shaded jar.
[INFO] Including za.co.absa.spline:spline-core-spark-adapter-2.4:jar:0.3.9 in the shaded jar.
[INFO] Including za.co.absa.spline:spline-persistence-mongo:jar:0.3.9 in the shaded jar.
[INFO] Including com.github.salat:salat-core_2.11:jar:1.11.2 in the shaded jar.
[INFO] Including org.mongodb:casbah-core_2.11:jar:3.1.1 in the shaded jar.
[INFO] Including org.mongodb:casbah-commons_2.11:jar:3.1.1 in the shaded jar.
[INFO] Including com.github.nscala-time:nscala-time_2.11:jar:1.0.0 in the shaded jar.
[INFO] Including org.mongodb:mongo-java-driver:jar:3.6.3 in the shaded jar.
[INFO] Including org.mongodb:casbah-query_2.11:jar:3.1.1 in the shaded jar.
[INFO] Including org.json4s:json4s-native_2.11:jar:3.5.3 in the shaded jar.
[INFO] Including za.co.absa.spline:spline-persistence-hdfs:jar:0.3.9 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-common:jar:2.6.5 in the shaded jar.
[INFO] Including commons-cli:commons-cli:jar:1.2 in the shaded jar.
[INFO] Including xmlenc:xmlenc:jar:0.52 in the shaded jar.
[INFO] Including commons-httpclient:commons-httpclient:jar:3.1 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:2.6 in the shaded jar.
[INFO] Including commons-collections:commons-collections:jar:3.2.2 in the shaded jar.
[INFO] Including javax.servlet:servlet-api:jar:2.5 in the shaded jar.
[INFO] Including org.mortbay.jetty:jetty:jar:6.1.26 in the shaded jar.
[INFO] Including org.mortbay.jetty:jetty-util:jar:6.1.26 in the shaded jar.
[INFO] Including com.sun.jersey:jersey-core:jar:1.9 in the shaded jar.
[INFO] Including com.sun.jersey:jersey-json:jar:1.9 in the shaded jar.
[INFO] Including org.codehaus.jettison:jettison:jar:1.1 in the shaded jar.
[INFO] Including com.sun.xml.bind:jaxb-impl:jar:2.2.3-1 in the shaded jar.
[INFO] Including org.codehaus.jackson:jackson-jaxrs:jar:1.8.3 in the shaded jar.
[INFO] Including org.codehaus.jackson:jackson-xc:jar:1.8.3 in the shaded jar.
[INFO] Including com.sun.jersey:jersey-server:jar:1.9 in the shaded jar.
[INFO] Including asm:asm:jar:3.1 in the shaded jar.
[INFO] Including tomcat:jasper-compiler:jar:5.5.23 in the shaded jar.
[INFO] Including tomcat:jasper-runtime:jar:5.5.23 in the shaded jar.
[INFO] Including javax.servlet.jsp:jsp-api:jar:2.1 in the shaded jar.
[INFO] Including commons-el:commons-el:jar:1.0 in the shaded jar.
[INFO] Including commons-logging:commons-logging:jar:1.1.3 in the shaded jar.
[INFO] Including net.java.dev.jets3t:jets3t:jar:0.9.0 in the shaded jar.
[INFO] Including org.apache.httpcomponents:httpclient:jar:4.1.2 in the shaded jar.
[INFO] Including org.apache.httpcomponents:httpcore:jar:4.1.2 in the shaded jar.
[INFO] Including com.jamesmurty.utils:java-xmlbuilder:jar:0.4 in the shaded jar.
[INFO] Including com.google.code.gson:gson:jar:2.2.4 in the shaded jar.
[INFO] Including org.apache.hadoop:hadoop-auth:jar:2.6.5 in the shaded jar.
[INFO] Including org.apache.directory.server:apacheds-kerberos-codec:jar:2.0.0-M15 in the shaded jar.
[INFO] Including org.apache.directory.server:apacheds-i18n:jar:2.0.0-M15 in the shaded jar.
[INFO] Including org.apache.directory.api:api-asn1-api:jar:1.0.0-M20 in the shaded jar.
[INFO] Including org.apache.directory.api:api-util:jar:1.0.0-M20 in the shaded jar.
[INFO] Including com.jcraft:jsch:jar:0.1.42 in the shaded jar.
[INFO] Including org.apache.curator:curator-client:jar:2.6.0 in the shaded jar.
[INFO] Including org.htrace:htrace-core:jar:3.0.4 in the shaded jar.
[INFO] Including org.json4s:json4s-ext_2.11:jar:3.5.3 in the shaded jar.
[INFO] Including org.joda:joda-convert:jar:1.8.1 in the shaded jar.
[INFO] Including za.co.absa.spline:spline-persistence-atlas:jar:0.3.9 in the shaded jar.
[INFO] Including org.apache.atlas:atlas-notification:jar:1.0.0 in the shaded jar.
[INFO] Including org.apache.atlas:atlas-client-v1:jar:1.0.0 in the shaded jar.
[INFO] Including org.apache.atlas:atlas-client-common:jar:1.0.0 in the shaded jar.
[INFO] Including com.sun.jersey:jersey-client:jar:1.19 in the shaded jar.
[INFO] Including com.sun.jersey.contribs:jersey-multipart:jar:1.19 in the shaded jar.
[INFO] Including org.jvnet.mimepull:mimepull:jar:1.9.3 in the shaded jar.
[INFO] Including org.apache.atlas:atlas-common:jar:1.0.0 in the shaded jar.
[INFO] Including org.springframework:spring-beans:jar:4.3.17.RELEASE in the shaded jar.
[INFO] Including org.apache.atlas:atlas-server-api:jar:1.0.0 in the shaded jar.
[INFO] Including org.apache.kafka:kafka-clients:jar:1.0.0 in the shaded jar.
[INFO] Including org.apache.kafka:kafka_2.11:jar:1.0.0 in the shaded jar.
[INFO] Including net.sf.jopt-simple:jopt-simple:jar:5.0.4 in the shaded jar.
[INFO] Including com.yammer.metrics:metrics-core:jar:2.2.0 in the shaded jar.
[INFO] Including com.101tec:zkclient:jar:0.8 in the shaded jar.
[INFO] Including cglib:cglib:jar:2.2.2 in the shaded jar.
[INFO] Including org.apache.atlas:atlas-intg:jar:1.0.0 in the shaded jar.
[INFO] Including com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.9.5 in the shaded jar.
[INFO] Including com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.9.5 in the shaded jar.
[INFO] Including com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.5 in the shaded jar.
[INFO] Including javax.inject:javax.inject:jar:1 in the shaded jar.
[INFO] Including org.springframework:spring-context:jar:4.3.17.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-aop:jar:4.3.17.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-core:jar:4.3.17.RELEASE in the shaded jar.
[INFO] Including org.springframework:spring-expression:jar:4.3.17.RELEASE in the shaded jar.
[INFO] Including com.databricks:spark-xml_2.11:jar:0.4.1 in the shaded jar.
[INFO] Including org.scala-lang.modules:scala-xml_2.11:jar:1.0.5 in the shaded jar.
[WARNING] jasper-runtime-5.5.23.jar, jasper-compiler-5.5.23.jar define 1 overlapping classes:
[WARNING]   - org.apache.jasper.compiler.Localizer
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing C:\Users\jh814289\IdeaProjects\spline-source-code\spline\sample\target\spline-sample-0.3.9.jar with C:\Users\jh814289\IdeaProjects\spline-source-code\spline\sam
ple\target\spline-sample-0.3.9-shaded.jar
[INFO] Dependency-reduced POM written at: C:\Users\jh814289\IdeaProjects\spline-source-code\spline\sample\dependency-reduced-pom.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:09 min
[INFO] Finished at: 2019-10-17T15:31:08-04:00
[INFO] ------------------------------------------------------------------------`
2.I copied the resulting jar to my spark-core folder 
3. I built my spark session with the following code. (I'm running my code in PyCharm)
`spark = SparkSession.builder \
	              .appName ( 'Spline_test' ) \
                     .config("spark.jars", "/spline-sample-0.3.9.jar")\
	              .getOrCreate ()`
4. I ran the following code
`sc._jvm.za.co.absa.spline.core.SparkLineageInitializer.enableLineageTracking(spark._jsparkSession)

spark.read \
    .option("header", "true") \
    .option("inferschema", "true") \
    .csv("/data/input/batch/wikidata.csv") \
    .write \
    .mode('overwrite') \
    .csv("/data/input/batch/python-sample.csv")`
4. The output I'm getting is 
`SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/rr249686/spark-2.4.1-bin-hadoop2.7/jars/spline-sample-0.3.9.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/rr249686/spark-2.4.1-bin-hadoop2.7/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
19/10/18 07:51:53 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
java.lang.NoClassDefFoundError: scala/tools/scalap/scalax/rules/scalasig/ByteCode$
	at salat.util.ScalaSigUtil$.parseClassFileFromByteCode(ScalaSigUtil.scala:39)
	at salat.util.ScalaSigUtil$.parseScalaSig0(ScalaSigUtil.scala:83)
	at salat.ClassAnalyzer$.findSym(ClassAnalyzer.scala:46)
	at salat.ClassAnalyzer.<init>(ClassAnalyzer.scala:136)
	at salat.ConcreteGrater.ca$lzycompute(Grater.scala:120)
	at salat.ConcreteGrater.ca(Grater.scala:120)
	at salat.ConcreteGrater.useTypeHint$lzycompute(Grater.scala:124)
	at salat.ConcreteGrater.useTypeHint(Grater.scala:123)
	at salat.ConcreteGrater.asDBObject(Grater.scala:291)
	at za.co.absa.spline.persistence.mongo.MongoDataLineageWriter.store(MongoDataLineageWriter.scala:32)
	at za.co.absa.spline.core.SparkLineageProcessor$$anonfun$2.apply(SparkLineageProcessor.scala:50)
	at za.co.absa.spline.core.SparkLineageProcessor$$anonfun$2.apply(SparkLineageProcessor.scala:49)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: scala.tools.scalap.scalax.rules.scalasig.ByteCode$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more
`

Hope this gives you more context.I did the same for spark-2.3 and I'm able to see lineage info. I'm also trying to replicate this on my Databricks instance as well. Please let me know if there's anything else I need to do.

I would really appreciate your help. Thanks

Roshna

**Comment by wajda** [comment]
Ok, I got it. The problem was in the documentation. It's outdated. Please **do not** call `mvn shade`. The sample fat-jar is assembled incorrectly.

Instead, build the Spline normally using the default profile `mvn install` (or `mvn install -DskipTests` for faster build), and then include corresponding `spline-bundle.jar` into your `pyspark` command. E.g.
```shell
pyspark \
--jars sample/target/spline-sample-0.3.9.jar,bundle-2.4/target/spline-bundle-2_4-0.3.9.jar \
--conf spark.spline.persistence.factory=za.co.absa.spline.persistence.mongo.MongoPersistenceFactory \
--conf spark.spline.mongodb.url=mongodb://localhost/aaa
```

Also you can use pyspark with the option `--packages` to include Spline bundle directly from Maven Central. You do not have to build Spline yourself.

```shell
pyspark \
--packages za.co.absa.spline:spline-bundle-2_4:0.3.9 \
--conf spark.spline.persistence.factory=za.co.absa.spline.persistence.mongo.MongoPersistenceFactory \
--conf spark.spline.mongodb.url=mongodb://localhost/aaa
```
