### ISSUE TITLE
Failure while migrating

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/spline#403]
## Run
```
java -jar migrator-tool-0.4.0-SNAPSHOT.jar -s mongodb://127.0.0.1:27017/spline -t http://localhost:9999/producer -e failFile.txt -b 20                                                                                                                                130 ↵
Processed: 24        Failures: 1         Speed [doc/sec]: 1.25      Load: [########..][ERROR] [10/22/2019 13:55:11.912] [system-akka.actor.default-dispatcher-5] [akka://system/user/batch-migrator/$c] 6131f8f3-9731-41e3-91da-afadd9dcdc52
za.co.absa.spline.migrator.rest.RestClient$HttpException: {"error_id":"2fa0bbb5-cb10-4215-86c6-bd2a7dc5c828"}
	at za.co.absa.spline.migrator.rest.RestClientPlayWsImpl$$anon$1$$anonfun$post$1.apply(RestClientPlayWsImpl.scala:42)
	at za.co.absa.spline.migrator.rest.RestClientPlayWsImpl$$anon$1$$anonfun$post$1.apply(RestClientPlayWsImpl.scala:40)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Processed: 186       Failures: 1         Speed [doc/sec]: 5.19      Load: [..........]
WARNING. Totally processed: 186 (of which successfully migrated: 185, failed: 1)
```

## STDOUT
```
13:59:09.269 [ForkJoinPool-1-worker-1] DEBUG com.arangodb.internal.velocystream.internal.VstConnection - Send chunk 2:0 from message 749
13:59:09.269 [ForkJoinPool-1-worker-1] DEBUG com.arangodb.internal.velocystream.internal.VstConnection - Send chunk 3:0 from message 749
13:59:09.269 [ForkJoinPool-1-worker-1] DEBUG com.arangodb.internal.velocystream.internal.VstConnection - Send chunk 4:0 from message 749
13:59:09.269 [ForkJoinPool-1-worker-1] DEBUG com.arangodb.internal.velocystream.internal.VstConnection - Send chunk 5:0 from message 749
13:59:09.279 [pool-1-thread-1] DEBUG com.arangodb.internal.velocystream.internal.VstConnection - Received chunk 1:1 from message 749
13:59:09.279 [pool-1-thread-1] DEBUG com.arangodb.internal.velocystream.internal.MessageStore - Received Message (id=749, head=[1,2,409,{}], body={"code":409,"error":true,"errorMessage":"unique constraint violated - in index primary of type primary over '_key'; conflicting key: 6131f8f3-9731-41e3-91da-afadd9dcdc52:5","errorNum":1210})
13:59:09.280 [ForkJoinPool-1-worker-29] DEBUG org.springframework.web.context.request.async.WebAsyncManager - Async error, dispatch to /producer/execution/plan
13:59:09.280 [http-bio-9999-exec-21] DEBUG org.springframework.web.servlet.DispatcherServlet - "ASYNC" dispatch for POST "/producer/execution/plan", parameters={}
13:59:09.280 [http-bio-9999-exec-21] DEBUG org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter - Resume with async result [com.arangodb.ArangoDBException: Response: 409, Error: 1210 - unique constraint violated - in index p (truncated)...]
13:59:09.280 [http-bio-9999-exec-21] DEBUG org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver - Using @ExceptionHandler public org.springframework.http.ResponseEntity<za.co.absa.spline.common.logging.ErrorCode> za.co.absa.spline.producer.rest.controller.ErrorControllerAdvice.handle_500(java.lang.Throwable)
13:59:09.281 [http-bio-9999-exec-21] ERROR za.co.absa.spline.common.logging.ErrorCode$ - ErrorCode(857f1a05-414a-4432-9249-5f7583d49107)
com.arangodb.ArangoDBException: Response: 409, Error: 1210 - unique constraint violated - in index primary of type primary over '_key'; conflicting key: 6131f8f3-9731-41e3-91da-afadd9dcdc52:5
	at com.arangodb.internal.velocystream.VstCommunicationAsync.lambda$execute$0(VstCommunicationAsync.java:132)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.arangodb.internal.velocystream.VstConnectionAsync$1.call(VstConnectionAsync.java:101)
	at com.arangodb.internal.velocystream.VstConnectionAsync$1.call(VstConnectionAsync.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.arangodb.internal.velocystream.internal.MessageStore.consume(MessageStore.java:64)
	at com.arangodb.internal.velocystream.internal.ChunkStore.checkCompleteness(ChunkStore.java:66)
	at com.arangodb.internal.velocystream.internal.ChunkStore.checkCompleteness(ChunkStore.java:60)
	at com.arangodb.internal.velocystream.internal.VstConnection$1.call(VstConnection.java:147)
	at com.arangodb.internal.velocystream.internal.VstConnection$1.call(VstConnection.java:124)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
13:59:09.281 [http-bio-9999-exec-21] DEBUG org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor - Using 'application/json', given [*/*] and supported [application/json, application/*+json]
13:59:09.281 [http-bio-9999-exec-21] DEBUG org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor - Writing [ErrorCode(857f1a05-414a-4432-9249-5f7583d49107)]
13:59:09.282 [http-bio-9999-exec-21] DEBUG org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver - Resolved [com.arangodb.ArangoDBException: Response: 409, Error: 1210 - unique constraint violated - in index primary of type primary over '_key'; conflicting key: 6131f8f3-9731-41e3-91da-afadd9dcdc52:5]
13:59:09.282 [http-bio-9999-exec-21] DEBUG org.springframework.web.servlet.DispatcherServlet - Exiting from "ASYNC" dispatch, status 500
```

## Zip of Mongo dump
Will be sent off GitHub

**Comment by wajda** [comment]
The error is non-deterministic. I was able to migrate all records using 10 threads and 20 threads. However on 50 threads there were plenty of errors.
On Sasa's PC the error appeared on 20 threads.

**Comment by Zejnilovic** [comment]
Problem was when trying to re-run just the 1 failed job, it still failed with the same error. Is this ok with your DB?

**Comment by wajda** [comment]
That's the point, I'm trying to find a way to reproduce it. For me it either works of fail for random but large number of docs. I just tried again using 50 threads and now migration succeeded. And it will definitely succeed in debug mode.

**Comment by Zejnilovic** [comment]
I seem not to be able to run `-r` successfully. Even when I try it again. 
But I am able to run it successfully by specifying `-b 2`

**Comment by wajda** [comment]
Ok, I got it. There were two things happening.
First of all, there was no real failure on the _Producer_ side. All documents are de facto processed and stored correctly even though there are lots of exceptions pops up in the logs everywhere. Those exceptions are all `AsyncRequestTimeoutException`, that can be sold by simply tuning the Tomcat's HTTP Connector.
Another problem was non-reentrancy of the _Migrator_. The reason why retrying with `-r` didn't work for Sasa is because that document was in fact successfully migrated during the previous run. And because aforementioned false timeout exception _Migrator_ marked it for retry. But due to lack of reentrancy the second attempt to migrate the doc that has already been migrated failed.
So both issues in combination created a lot of confusion.

**Comment by wajda** [comment]
The timeouts only happen when running REST-gateway in the embedded mode (exec.jar). It could be either due to the improper default config, or it can be related to the old Tomcat 7.0 version in use.
I couldn't find any way to tweak the embedded tomcat. The only existing option is to use `-serverXmlPath` command-line argument when running the exec-jar. That's inconvenient and pretty much defeats the purpose of Exec-jar.
So, the best way to solve timeout problem would be to replace the current exec-jar with a Spline docker container built on top of Tomcat 9. #249

**Comment by wajda** [comment]
I will solve reentrance issue by checking the given execPlan ID for existence in the database. If one is found the given execPlan will be skipped.

**Comment by Zejnilovic** [comment]
LGTM
