### ISSUE TITLE
Concurrency issue with Atlas and Mongo persistence

### ISSUE THREAD

**Issue by rjbarrington** [AbsaOSS/spline#42]
In 0.3.1, I found that running Atlas and Mongo persistence in parallel results in errors about not finding (operation?) keys. This was consistently reproducible with SampleJob2, however SampleJob1 and SampleJob3 were OK. They all ran OK with Atlas and HDFS in parallel, or Mongo and HDFS in parallel:
```
18/06/07 17:02:06 INFO  FileFormatWriter:54 - Job null committed.
18/06/07 17:02:06 INFO  FileFormatWriter:54 - Finished processing stats for job null.
18/06/07 17:02:06 WARN util.ExecutionListenerManager: Error executing query execution listener
java.util.NoSuchElementException: key not found: f46f8f35-4c09-40a2-b09b-0ca4a5f7f99f
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at za.co.absa.spline.persistence.atlas.conversion.OperationConverter$$anonfun$convert$1$$anonfun$1.apply(OperationConverter.scala:41)
	at za.co.absa.spline.persistence.atlas.conversion.OperationConverter$$anonfun$convert$1$$anonfun$1.apply(OperationConverter.scala:41)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at za.co.absa.spline.persistence.atlas.conversion.OperationConverter$$anonfun$convert$1.apply(OperationConverter.scala:41)
	at za.co.absa.spline.persistence.atlas.conversion.OperationConverter$$anonfun$convert$1.apply(OperationConverter.scala:37)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at za.co.absa.spline.persistence.atlas.conversion.OperationConverter$.convert(OperationConverter.scala:37)
	at za.co.absa.spline.persistence.atlas.conversion.DataLineageToTypeSystemConverter$.convert(DataLineageToTypeSystemConverter.scala:36)
	at za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter$$anonfun$store$1.apply$mcV$sp(AtlasDataLineageWriter.scala:42)
	at za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter$$anonfun$store$1.apply(AtlasDataLineageWriter.scala:41)
	at za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter$$anonfun$store$1.apply(AtlasDataLineageWriter.scala:41)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
18/06/07 17:02:06 INFO spark.SparkContext: Invoking stop() from shutdown hook
```

**Comment by vackosar** [comment]
Can you share your configuration?

**Comment by rjbarrington** [comment]
Something like this in spline.properties, run via spark-submit --class za.co.absa.spline.sample.batch.SampleJob2 spline-sample-0.3.1.jar

```
# Spline lineage config
spline.persistence.factory=za.co.absa.spline.persistence.api.composition.ParallelCompositeFactory
spline.persistence.composition.factories=za.co.absa.spline.persistence.atlas.AtlasPersistenceFactory,za.co.absa.spline.persistence.mongo.MongoPersistenceFactory

# MongoDB config for UI
spline.mongodb.url=mongodb://bar.domain:27017
spline.mongodb.name=spline

# Atlas Kafka config
atlas.kafka.bootstrap.servers=foo.domain:9027

# Combinations tested with Spline SampleJob2
# HDFS + Atlas + Mongo = fail
#spline.persistence.composition.factories=za.co.absa.spline.persistence.hdfs.HdfsPersistenceFactory,za.co.absa.spline.persistence.atlas.AtlasPersistenceFactory,za.co.absa.spline.persistence.mongo.MongoPersistenceFactory
# Atlas + Mongo = fail
#spline.persistence.composition.factories=za.co.absa.spline.persistence.atlas.AtlasPersistenceFactory,za.co.absa.spline.persistence.mongo.MongoPersistenceFactory
# HDFS + Atlas = works
#spline.persistence.composition.factories=za.co.absa.spline.persistence.hdfs.HdfsPersistenceFactory,za.co.absa.spline.persistence.atlas.AtlasPersistenceFactory
# HDFS + Mongo = works
#spline.persistence.composition.factories=za.co.absa.spline.persistence.hdfs.HdfsPersistenceFactory,za.co.absa.spline.persistence.mongo.MongoPersistenceFactory
```

**Comment by vackosar** [comment]
hm I can see mutable ArrayBuffer in the stack that could be the problem.

**Comment by vackosar** [comment]
I reproduced the exception. I will have a quick look now.

**Comment by vackosar** [comment]
This is caused by simultaneously linking to other lineages and saving to Atlas as well. I will implement fix storing non-linked lineages only to Atlas.

**Comment by vackosar** [comment]
The fix commit is available on release branch 0.3 here: 179283e0cc2c50036fec54a3d41290ef537c422f
I dont want to release new release just yet due to significant overhead of it.
Can you build it from the source using the snapshot version at the moment?

**Comment by vackosar** [comment]
Let me know if u have issues with above solution.

**Comment by rjbarrington** [comment]
Sorry, got busy. I'll have a look this weekend.

**Comment by rjbarrington** [comment]
Yep, that works for me.
