### ISSUE TITLE
Search by attribute name

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#442]
> What kind of information would you like to search?

by column name
Currently in 0.3.9 if we like to know a position of a column in a lineage graph, we have to click through bunch of nodes(projection or aggregation of filter) to find the column and click on the right detail list to look up the lineage in orange. It'd be the best to search by column name then UI can list all possible nodes, then when user click on each search result it would be just like click on the associated node in the graph.

_Originally posted by @iamgzy in https://github.com/AbsaOSS/spline/issues/428#issuecomment-548956567_

**Comment by cerveada** [comment]
Rest API:
INPUT: attribute name (any string)
OUTPUT: attribute ID, execution event ID

The backend should search for all attributes that are on output of any execution plan. For the same write target only the attribute form the latest executed execution should be returned.

**Comment by Zejnilovic** [comment]
When I input `ID1` in search box I get `500` response in UI and `404` on rest server-side saying: 

```
java.util.concurrent.CompletionException: com.arangodb.ArangoDBException: Response: 404, Error: 1203 - AQL: collection or view not found: attributeSearchView (while parsing)
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925)
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:913)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at com.arangodb.async.internal.velocystream.VstCommunicationAsync.lambda$execute$0(VstCommunicationAsync.java:66)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at com.arangodb.async.internal.velocystream.VstConnectionAsync.lambda$write$0(VstConnectionAsync.java:48)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.arangodb.internal.velocystream.internal.MessageStore.consume(MessageStore.java:62)
	at com.arangodb.internal.velocystream.internal.ChunkStore.checkCompleteness(ChunkStore.java:65)
	at com.arangodb.internal.velocystream.internal.ChunkStore.checkCompleteness(ChunkStore.java:59)
	at com.arangodb.internal.velocystream.internal.VstConnection.lambda$open$0(VstConnection.java:151)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.arangodb.ArangoDBException: Response: 404, Error: 1203 - AQL: collection or view not found: attributeSearchView (while parsing)
	... 15 common frames omitted
```

Even if this is a normal "did not find", I don't expect a 500 on the UI side.

**Comment by wajda** [comment]
`java -jar admin-cli.jar db-upgrade`

**Comment by Zejnilovic** [comment]
Thank you. The upgrade did help but I still have to ask for help once more. I don't get this.

![Apr-09-2020 12-33-19](https://user-images.githubusercontent.com/17467768/78886391-677d4980-7a5e-11ea-8a88-40445f551815.gif)

**Comment by Zejnilovic** [comment]
And it seems to me that the Detailed Lineage is not updating it's view when I change pick something new. Not sure if related

**Comment by wajda** [comment]
Yep, same thing.
This feature isn't 100% ready and is logically bound to #451 which is progress atm.
Will fix it there.
