### ISSUE TITLE
NPE in Consumer

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#443]
GET http://localhost:8080/consumer/operation/be63d3f4-de1a-4db9-9bf4-b06aad25fdb5:4
```
21:02:19.751 [http-nio-8080-exec-3] ERROR z.c.a.s.common.logging.ErrorCode$ - ErrorCode(cd355a5d-fb01-4ae7-8e98-08a837f83381)
java.lang.NullPointerException: null
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192)
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192)
	at scala.collection.SeqLike$class.size(SeqLike.scala:106)
	at scala.collection.mutable.ArrayOps$ofRef.size(ArrayOps.scala:186)
	at scala.collection.mutable.Builder$class.sizeHint(Builder.scala:69)
	at scala.collection.mutable.ArrayBuilder.sizeHint(ArrayBuilder.scala:22)
	at scala.collection.TraversableLike$class.builder$1(TraversableLike.scala:230)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:233)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at za.co.absa.spline.consumer.rest.controller.OperationDetailsController$$anonfun$getAllIds$1.apply(OperationDetailsController.scala:77)
	at za.co.absa.spline.consumer.rest.controller.OperationDetailsController$$anonfun$getAllIds$1.apply(OperationDetailsController.scala:74)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:316)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at za.co.absa.spline.consumer.rest.controller.OperationDetailsController.getAllIds(OperationDetailsController.scala:74)
	at za.co.absa.spline.consumer.rest.controller.OperationDetailsController.dataTypesFilter(OperationDetailsController.scala:66)
	at za.co.absa.spline.consumer.rest.controller.OperationDetailsController.reducedDataTypes(OperationDetailsController.scala:60)
	at za.co.absa.spline.consumer.rest.controller.OperationDetailsController.za$co$absa$spline$consumer$rest$controller$OperationDetailsController$$toOperationDetails(OperationDetailsController.scala:53)
	at za.co.absa.spline.consumer.rest.controller.OperationDetailsController$$anonfun$operation$1.apply(OperationDetailsController.scala:48)
	at za.co.absa.spline.consumer.rest.controller.OperationDetailsController$$anonfun$operation$1.apply(OperationDetailsController.scala:48)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by wajda** [comment]
It was an outdated data schema issue. Closing as invalid
