### ISSUE TITLE
Maven Build Failing in developer branch

### ISSUE THREAD

**Issue by devshank** [AbsaOSS/spline#480]
I am trying to build the code in the develop branch. It fails in the **commons** module.

**LOGS:**
```
[INFO] java.lang.reflect.InvocationTargetException
[INFO]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO]  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[INFO]  at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[INFO]  at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[ERROR] Caused by: java.lang.NoClassDefFoundError: javax/tools/ToolProvider
[INFO]  at scala.reflect.io.JavaToolsPlatformArchive.iterator(ZipArchive.scala:301)
[INFO]  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[INFO]  at scala.reflect.io.AbstractFile.foreach(AbstractFile.scala:92)
[INFO]  at scala.tools.nsc.util.DirectoryClassPath.traverse(ClassPath.scala:277)
[INFO]  at scala.tools.nsc.util.DirectoryClassPath.x$15$lzycompute(ClassPath.scala:299)
[INFO]  at scala.tools.nsc.util.DirectoryClassPath.x$15(ClassPath.scala:299)
[INFO]  at scala.tools.nsc.util.DirectoryClassPath.packages$lzycompute(ClassPath.scala:299)
[INFO]  at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:299)
[INFO]  at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:264)
[INFO]  at scala.tools.nsc.util.MergedClassPath$$anonfun$packages$1.apply(ClassPath.scala:358)
[INFO]  at scala.tools.nsc.util.MergedClassPath$$anonfun$packages$1.apply(ClassPath.scala:358)
[INFO]  at scala.collection.Iterator$class.foreach(Iterator.scala:891)
[INFO]  at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
[INFO]  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[INFO]  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[INFO]  at scala.tools.nsc.util.MergedClassPath.packages$lzycompute(ClassPath.scala:358)
[INFO]  at scala.tools.nsc.util.MergedClassPath.packages(ClassPath.scala:353)
[INFO]  at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader$$anonfun$doComplete$1.apply$mcV$sp(SymbolLoaders.scala:269)
[INFO]  at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader$$anonfun$doComplete$1.apply(SymbolLoaders.scala:260)
[INFO]  at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader$$anonfun$doComplete$1.apply(SymbolLoaders.scala:260)
[INFO]  at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:235)
[INFO]  at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:260)
[INFO]  at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:211)
[INFO]  at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1535)
[INFO]  at scala.reflect.internal.Mirrors$RootsBase.init(Mirrors.scala:256)
[INFO]  at scala.tools.nsc.Global.rootMirror$lzycompute(Global.scala:73)
[INFO]  at scala.tools.nsc.Global.rootMirror(Global.scala:71)
[INFO]  at scala.tools.nsc.Global.rootMirror(Global.scala:39)
[INFO]  at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
[INFO]  at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
[INFO]  at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1390)
[INFO]  at scala.tools.nsc.Global$Run.<init>(Global.scala:1242)
[INFO]  at scala.tools.nsc.Driver.doCompile(Driver.scala:31)
[INFO]  at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
[INFO]  at scala.tools.nsc.Driver.process(Driver.scala:51)
[INFO]  at scala.tools.nsc.Driver.main(Driver.scala:64)
[INFO]  at scala.tools.nsc.Main.main(Main.scala)
[INFO]  ... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for spline 0.4.0-SNAPSHOT:
[INFO]
[INFO] Spline ............................................. SUCCESS [ 13.295 s]
[INFO] commons ............................................ FAILURE [ 16.765 s]
[INFO] producer-rest-model ................................ SKIPPED
[INFO] spark-agent ........................................ SKIPPED
[INFO] migrator-tool ...................................... SKIPPED
[INFO] rest-api-doc-generator ............................. SKIPPED
[INFO] persistence ........................................ SKIPPED
[INFO] producer-services .................................. SKIPPED
[INFO] consumer-services .................................. SKIPPED
[INFO] producer-rest-core ................................. SKIPPED
[INFO] consumer-rest-core ................................. SKIPPED
[INFO] rest-gateway ....................................... SKIPPED
[INFO] admin .............................................. SKIPPED
[INFO] client-ui .......................................... SKIPPED
[INFO] absaoss-spline-client .............................. SKIPPED
[INFO] client-web ......................................... SKIPPED
[INFO] spark-bundle-2.2 ................................... SKIPPED
[INFO] spark-bundle-2.3 ................................... SKIPPED
[INFO] spark-bundle-2.4 ................................... SKIPPED
[INFO] examples ........................................... SKIPPED
[INFO] integration-tests .................................. SKIPPED
[INFO] spline ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30.731 s
[INFO] Finished at: 2019-11-27T12:33:25Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.3.1:compile (scala-compile) on project commons: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240 (Exit value: 240) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :commons
```

![image](https://user-images.githubusercontent.com/29790745/69725619-8f6daf80-1144-11ea-9391-937cfff7c1a5.png)

![image](https://user-images.githubusercontent.com/29790745/69725673-ae6c4180-1144-11ea-92a3-bd1fd56c89d2.png)

**Comment by wajda** [comment]
This is the problem:
```
[ERROR] Caused by: java.lang.NoClassDefFoundError: javax/tools/ToolProvider
```
What Java version are you using?

**Comment by devshank** [comment]
Yes, I could see this in the logs. I have been using different versions of Java. 
I used openjdk 7-11 and Oracle JDK 8-11, all of which are failing during build time.

**Comment by wajda** [comment]
Please use JDK 8. It doesn't matter if it's Oracle or OpenJDK, but has to be 8.

**Comment by dmudro** [comment]
Had the same issue when using JDK > 8. [jEnv](https://www.jenv.be) helps too as I want to have multiple versions of Java available on the same system.

**Comment by devshank** [comment]
Thanks, this works. Closing this issue.

**Comment by devshank** [comment]
> Please use JDK 8. It doesn't matter if it's Oracle or OpenJDK, but has to be 8.

Thanks, this works. Closing this issue.
