### ISSUE TITLE
[client-web] fail to access path /app, due to Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class za.co.absa.spline.client.web.AppConfig$Consumer$

### ISSUE THREAD

**Issue by hugeshi** [AbsaOSS/spline#508]
https://repo1.maven.org/maven2/za/co/absa/spline/client-web/0.4.0/client-web-0.4.0.war
I download the upper war and put to webapps under tomcat 8, I can access the path "/build-info", but fail to access /app. the error is Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class za.co.absa.spline.client.web.AppConfig$Consumer$

the below is snapshot of error:
![image](https://user-images.githubusercontent.com/6722878/70221803-f19d6480-1783-11ea-9c55-8b3599af7942.png)

**Comment by wajda** [comment]
Looks like a deployment issue on your side. I just retested it with that exact WAR and everything works fine. I'm using Tomcat 9, not sure if that's related though.
Please make sure you are using Java 8, clean the tomcat temp and work dirs and try again.

**Comment by wajda** [comment]
There is also a docker image, did you try that one?
https://hub.docker.com/repository/docker/absaoss/spline-web-client

**Comment by hugeshi** [comment]
I have tried several times. but always fail due to this issue. I have no idea now. I use mac and JDK is 1.8.0_221, but I can manage to run with docker image. feel free to close it if you like

**Comment by wajda** [comment]
What you can do is to take a look at Tomcat's extracted `webapp/spline-web-client/WEB-INF` directory, and see it the aforementioned class file is physically there.

**Comment by wajda** [comment]
I was able to reproduced it.
You probably didn't specify the `spline.consumer.url` config parameter.
For some reason when deploying a WAR-file Tomcat doesn't show the original error which in case should be `java.lang.IllegalArgumentException: requirement failed: Missing configuration property spline.consumer.url`

Please make sure you have set `spline.consumer.url` either as a JVM property, environment variable or JNDI entry.

**Comment by wajda** [comment]
After looking at it more carefully I noticed that the error message that you posted is actually the message that Tomcat shows on subsequent attempts to load the page, but the original message is displayed on the first page request.
The original message is also in the server logs.
```
09-Dec-2019 14:33:15.360 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [dispatcher] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.ExceptionInInitializerError] with root cause
	java.lang.IllegalArgumentException: requirement failed: Missing configuration property spline.consumer.url
		at scala.Predef$.require(Predef.scala:224)
		at za.co.absa.spline.common.ConfigurationImplicits$ConfigurationRequiredWrapper.za$co$absa$spline$common$ConfigurationImplicits$ConfigurationRequiredWrapper$$getRequired(ConfigurationImplicits.scala:107)
		at za.co.absa.spline.common.ConfigurationImplicits$ConfigurationRequiredWrapper$$anonfun$getRequiredString$3.apply(ConfigurationImplicits.scala:40)
		at za.co.absa.spline.common.ConfigurationImplicits$ConfigurationRequiredWrapper$$anonfun$getRequiredString$3.apply(ConfigurationImplicits.scala:40)
		at za.co.absa.spline.client.web.AppConfig$Consumer$.<init>(AppConfig.scala:29)
		at za.co.absa.spline.client.web.AppConfig$Consumer$.<clinit>(AppConfig.scala)
		at za.co.absa.spline.client.web.WebController.index(WebController.scala:45)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
		at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
		at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
		at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
		at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
		at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
		at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
		at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
		at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
		at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
		at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
```

So, if this is the case you are experiencing then I think the issue can be closed.

**Comment by hugeshi** [comment]
thanks for your feedback. we can close this issue
