### ISSUE TITLE
Cannot re-attempt Spline initialization after an error

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#533]
In Spark shell when I forgot to provide `spline.producer.url` Spline init fails due to missing configuration property as expected. But after that happens I have to close and open Spark shell again to re-attempt Spline init. Otherwise it says that Spline has already been initialized, even though it's actually not.

```
Using Scala version 2.11.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_232)
Type in expressions to have them evaluated.
Type :help for more information.

scala> import za.co.absa.spline.harvester.SparkLineageInitializer
import za.co.absa.spline.harvester.SparkLineageInitializer

scala> SparkLineageInitializer.enableLineageTracking(spark)
19/12/16 16:41:51 ERROR SparkLineageInitializer$: Spline initialization failed! Spark Lineage tracking is DISABLED.
java.lang.IllegalArgumentException: requirement failed: Missing configuration property spline.producer.url
	at scala.Predef$.require(Predef.scala:224)
	at za.co.absa.spline.common.ConfigurationImplicits$ConfigurationRequiredWrapper.za$co$absa$spline$common$ConfigurationImplicits$ConfigurationRequiredWrapper$$getRequired(ConfigurationImplicits.scala:107)
	at za.co.absa.spline.common.ConfigurationImplicits$ConfigurationRequiredWrapper$$anonfun$getRequiredString$3.apply(ConfigurationImplicits.scala:40)
	at za.co.absa.spline.common.ConfigurationImplicits$ConfigurationRequiredWrapper$$anonfun$getRequiredString$3.apply(ConfigurationImplicits.scala:40)
	at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher$.apply(HttpLineageDispatcher.scala:87)
	at za.co.absa.spline.harvester.conf.DefaultSplineConfigurer.lineageDispatcher$lzycompute(DefaultSplineConfigurer.scala:75)
	at za.co.absa.spline.harvester.conf.DefaultSplineConfigurer.lineageDispatcher(DefaultSplineConfigurer.scala:73)
	at za.co.absa.spline.harvester.conf.DefaultSplineConfigurer.queryExecutionEventHandler(DefaultSplineConfigurer.scala:90)
	at za.co.absa.spline.harvester.SparkLineageInitializer$SparkSessionWrapper.createEventHandler(SparkLineageInitializer.scala:110)
	at za.co.absa.spline.harvester.SparkLineageInitializer$SparkSessionWrapper.enableLineageTracking(SparkLineageInitializer.scala:83)
	at za.co.absa.spline.harvester.SparkLineageInitializer$.enableLineageTracking(SparkLineageInitializer.scala:39)
	at $line15.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:25)
	at $line15.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:30)
	at $line15.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:32)
	at $line15.$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:34)
	at $line15.$read$$iw$$iw$$iw$$iw.<init>(<console>:36)
	at $line15.$read$$iw$$iw$$iw.<init>(<console>:38)
	at $line15.$read$$iw$$iw.<init>(<console>:40)
	at $line15.$read$$iw.<init>(<console>:42)
	at $line15.$read.<init>(<console>:44)
	at $line15.$read$.<init>(<console>:48)
	at $line15.$read$.<clinit>(<console>)
	at $line15.$eval$.$print$lzycompute(<console>:7)
	at $line15.$eval$.$print(<console>:6)
	at $line15.$eval.$print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:819)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:691)
	at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:404)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:425)
	at org.apache.spark.repl.SparkILoop$$anonfun$process$1.apply$mcZ$sp(SparkILoop.scala:285)
	at org.apache.spark.repl.SparkILoop.runClosure(SparkILoop.scala:159)
	at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:182)
	at org.apache.spark.repl.Main$.doMain(Main.scala:78)
	at org.apache.spark.repl.Main$.main(Main.scala:58)
	at org.apache.spark.repl.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
res0: org.apache.spark.sql.SparkSession = org.apache.spark.sql.SparkSession@7a02d760

scala> SparkLineageInitializer.enableLineageTracking(spark)
19/12/16 16:41:55 WARN SparkLineageInitializer$: Spline lineage tracking is already initialized!
res1: org.apache.spark.sql.SparkSession = org.apache.spark.sql.SparkSession@7a02d760

scala> 

```

**Comment by wajda** [comment]
Makes sense to implement together with #432 as both tasks will likely require changes in the `SparkLineageInitializer`
