### ISSUE TITLE
spark-shell / pyspark --packages not working

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#535]
```
[wajda@alex-xps spline]$ /opt/spark-24/bin/spark-shell --packages za.co.absa.spline:spark-agent-bundle-2.4:0.4.0  --conf "spark.spline.producer.url=http://localhost:8080/producer"
Ivy Default Cache set to: /home/wajda/.ivy2/cache
The jars for the packages stored in: /home/wajda/.ivy2/jars
:: loading settings :: url = jar:file:/opt/spark-2.4.4-bin-hadoop2.7/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
za.co.absa.spline#spark-agent-bundle-2.4 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-5fca6813-067f-4213-8b51-ed08f182c463;1.0
	confs: [default]
	found za.co.absa.spline#spark-agent-bundle-2.4;0.4.0 in central
	found za.co.absa.spline#spark-agent;0.4.0 in central
	found org.scala-lang#scala-compiler;2.11.12 in local-m2-cache
	found org.scala-lang#scala-reflect;2.11.12 in local-m2-cache
	found org.scala-lang.modules#scala-xml_2.11;1.0.5 in local-m2-cache
	found org.scala-lang.modules#scala-parser-combinators_2.11;1.1.0 in local-m2-cache
	found za.co.absa.spline#commons;0.4.0 in central
	found commons-configuration#commons-configuration;1.6 in local-m2-cache
	found commons-collections#commons-collections;3.2.2 in local-m2-cache
	found commons-lang#commons-lang;2.6 in local-m2-cache
	found commons-logging#commons-logging;1.1.3 in local-m2-cache
	found commons-digester#commons-digester;1.8 in local-m2-cache
	found commons-beanutils#commons-beanutils;1.9.3 in local-m2-cache
	found commons-beanutils#commons-beanutils-core;1.8.0 in local-m2-cache
	found commons-io#commons-io;2.4 in local-m2-cache
	found org.apache.commons#commons-lang3;3.5 in local-m2-cache
	found org.slf4s#slf4s-api_2.11;1.7.25 in local-m2-cache
	found org.slf4j#slf4j-api;1.7.16 in local-m2-cache
	found za.co.absa.spline#producer-model;0.4.0 in central
	found com.databricks#spark-xml_2.11;0.4.1 in local-m2-cache
	found org.scalaz#scalaz-core_2.11;7.2.27 in local-m2-cache
	found org.scalaj#scalaj-http_2.11;2.4.1 in local-m2-cache
:: resolution report :: resolve 843ms :: artifacts dl 17ms
	:: modules in use:
	com.databricks#spark-xml_2.11;0.4.1 from local-m2-cache in [default]
	commons-beanutils#commons-beanutils;1.9.3 from local-m2-cache in [default]
	commons-beanutils#commons-beanutils-core;1.8.0 from local-m2-cache in [default]
	commons-collections#commons-collections;3.2.2 from local-m2-cache in [default]
	commons-configuration#commons-configuration;1.6 from local-m2-cache in [default]
	commons-digester#commons-digester;1.8 from local-m2-cache in [default]
	commons-io#commons-io;2.4 from local-m2-cache in [default]
	commons-lang#commons-lang;2.6 from local-m2-cache in [default]
	commons-logging#commons-logging;1.1.3 from local-m2-cache in [default]
	org.apache.commons#commons-lang3;3.5 from local-m2-cache in [default]
	org.scala-lang#scala-compiler;2.11.12 from local-m2-cache in [default]
	org.scala-lang#scala-reflect;2.11.12 from local-m2-cache in [default]
	org.scala-lang.modules#scala-parser-combinators_2.11;1.1.0 from local-m2-cache in [default]
	org.scala-lang.modules#scala-xml_2.11;1.0.5 from local-m2-cache in [default]
	org.scalaj#scalaj-http_2.11;2.4.1 from local-m2-cache in [default]
	org.scalaz#scalaz-core_2.11;7.2.27 from local-m2-cache in [default]
	org.slf4j#slf4j-api;1.7.16 from local-m2-cache in [default]
	org.slf4s#slf4s-api_2.11;1.7.25 from local-m2-cache in [default]
	za.co.absa.spline#commons;0.4.0 from central in [default]
	za.co.absa.spline#producer-model;0.4.0 from central in [default]
	za.co.absa.spline#spark-agent;0.4.0 from central in [default]
	za.co.absa.spline#spark-agent-bundle-2.4;0.4.0 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   23  |   0   |   0   |   0   ||   22  |   0   |
	---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
		module not found: org.json4s#json4s-ext_2.11;${json4s.version}

	==== local-m2-cache: tried

	  file:/home/wajda/.m2/repository/org/json4s/json4s-ext_2.11/${json4s.version}/json4s-ext_2.11-${json4s.version}.pom

	  -- artifact org.json4s#json4s-ext_2.11;${json4s.version}!json4s-ext_2.11.jar:

	  file:/home/wajda/.m2/repository/org/json4s/json4s-ext_2.11/${json4s.version}/json4s-ext_2.11-${json4s.version}.jar

	==== local-ivy-cache: tried

	  /home/wajda/.ivy2/local/org.json4s/json4s-ext_2.11/${json4s.version}/ivys/ivy.xml

	  -- artifact org.json4s#json4s-ext_2.11;${json4s.version}!json4s-ext_2.11.jar:

	  /home/wajda/.ivy2/local/org.json4s/json4s-ext_2.11/${json4s.version}/jars/json4s-ext_2.11.jar

	==== central: tried

	  https://repo1.maven.org/maven2/org/json4s/json4s-ext_2.11/${json4s.version}/json4s-ext_2.11-${json4s.version}.pom

	  -- artifact org.json4s#json4s-ext_2.11;${json4s.version}!json4s-ext_2.11.jar:

	  https://repo1.maven.org/maven2/org/json4s/json4s-ext_2.11/${json4s.version}/json4s-ext_2.11-${json4s.version}.jar

	==== spark-packages: tried

	  https://dl.bintray.com/spark-packages/maven/org/json4s/json4s-ext_2.11/${json4s.version}/json4s-ext_2.11-${json4s.version}.pom

	  -- artifact org.json4s#json4s-ext_2.11;${json4s.version}!json4s-ext_2.11.jar:

	  https://dl.bintray.com/spark-packages/maven/org/json4s/json4s-ext_2.11/${json4s.version}/json4s-ext_2.11-${json4s.version}.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.json4s#json4s-ext_2.11;${json4s.version}: not found

		::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.json4s#json4s-ext_2.11;${json4s.version}: not found]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1302)
	at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:304)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:774)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[wajda@alex-xps spline]$ 
```

**Comment by wajda** [comment]
fixed in the scope of #212
