### ISSUE TITLE
Spline Spark Agent dependacy setup

### ISSUE THREAD

**Issue by bgopal-nlg** [AbsaOSS/spline#551]
Installed pyspark 2.4 in windows 10 - executed the spline spark agent  dependency which is throwing an error.
Copied spark-agent-bundle-2.4-0.4.1.jar into  C:\SPARK\spark-2.4.4-bin-hadoop2.7\jars folder.
executed `pyspark ----packages "za.co.absa.spline.agent.spark:agent-core:0.4.1"`
throwing error as below..
```
C:\Users\HA2050>pyspark --packages "za.co.absa.spline.agent.spark:agent-core:0.4.1"
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
Ivy Default Cache set to: C:\Users\HA2050\.ivy2\cache
The jars for the packages stored in: C:\Users\HA2050\.ivy2\jars
:: loading settings :: url = jar:file:/C:/SPARK/spark-2.4.4-bin-hadoop2.7/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
za.co.absa.spline.agent.spark#agent-core added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-58947001-02f7-41eb-b23b-ab38058cc447;1.0
        confs: [default]
:: resolution report :: resolve 1725ms :: artifacts dl 0ms
        :: modules in use:
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
        ---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
                module not found: za.co.absa.spline.agent.spark#agent-core;0.4.1

        ==== local-m2-cache: tried

          file:/C:/Users/HA2050/.m2/repository/za/co/absa/spline/agent/spark/agent-core/0.4.1/agent-core-0.4.1.pom

          -- artifact za.co.absa.spline.agent.spark#agent-core;0.4.1!agent-core.jar:

          file:/C:/Users/HA2050/.m2/repository/za/co/absa/spline/agent/spark/agent-core/0.4.1/agent-core-0.4.1.jar

        ==== local-ivy-cache: tried

          C:\Users\HA2050\.ivy2\local\za.co.absa.spline.agent.spark\agent-core\0.4.1\ivys\ivy.xml

          -- artifact za.co.absa.spline.agent.spark#agent-core;0.4.1!agent-core.jar:

          C:\Users\HA2050\.ivy2\local\za.co.absa.spline.agent.spark\agent-core\0.4.1\jars\agent-core.jar

        ==== central: tried

          https://repo1.maven.org/maven2/za/co/absa/spline/agent/spark/agent-core/0.4.1/agent-core-0.4.1.pom

          -- artifact za.co.absa.spline.agent.spark#agent-core;0.4.1!agent-core.jar:

          https://repo1.maven.org/maven2/za/co/absa/spline/agent/spark/agent-core/0.4.1/agent-core-0.4.1.jar

        ==== spark-packages: tried

          https://dl.bintray.com/spark-packages/maven/za/co/absa/spline/agent/spark/agent-core/0.4.1/agent-core-0.4.1.pom

          -- artifact za.co.absa.spline.agent.spark#agent-core;0.4.1!agent-core.jar:

          https://dl.bintray.com/spark-packages/maven/za/co/absa/spline/agent/spark/agent-core/0.4.1/agent-core-0.4.1.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: za.co.absa.spline.agent.spark#agent-core;0.4.1: not found

                ::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: za.co.absa.spline.agent.spark#agent-core;0.4.1: not found]
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1302)
        at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
        at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:304)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:774)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Traceback (most recent call last):
  File "C:\SPARK\spark-2.4.4-bin-hadoop2.7\bin\..\python\pyspark\shell.py", line 38, in <module>
    SparkContext._ensure_initialized()
  File "C:\SPARK\spark-2.4.4-bin-hadoop2.7\python\pyspark\context.py", line 316, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "C:\SPARK\spark-2.4.4-bin-hadoop2.7\python\pyspark\java_gateway.py", line 46, in launch_gateway
    return _launch_gateway(conf)
  File "C:\SPARK\spark-2.4.4-bin-hadoop2.7\python\pyspark\java_gateway.py", line 108, in _launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number
```

**Comment by Zejnilovic** [comment]
1. Do you not see the bug template set up?
2. Spline dependency not found by your local environment doesn't sound like a Spline issue.
3. Have you tried activating your conda environment and/or checking if another jar works?

**Comment by wajda** [comment]
@bgopal-nlg 
I already warned you about this in the [other thread](https://github.com/AbsaOSS/spline/issues/524#issuecomment-574265129)
> Also, when uploading spline agent bundle to the Databricks choose upload as a JAR. Do not use Maven coordinates as it will most likely not work in Spline 0.4. (See #535)
