### ISSUE TITLE
Custom LineageDispatecher

### ISSUE THREAD

**Issue by dKiwi** [AbsaOSS/spline#578]
I have a problem with running a custom dispatcher. This may or may not be related to the fact, that I'm using Databricks with a specific runtime version, but that's part of the issue I'm trying to tackle.

I extended the trait and added za.co.absa.spline:admin:0.4.1 and za.co.absa.spline:admin:0.4.1 to the Databricks cluster. The following cell runs fine.

```
System.setProperty("spline.mode","REQUIRED")
System.setProperty("spline.lineage_dispatcher.className", "my_class")
import za.co.absa.spline.harvester.SparkLineageInitializer._
spark.enableLineageTracking()
```

However, when I attempt to read a table and write it to Gen2 (and as an external table). I get the error as follows. Any hints would be most appreciated.

```
java.lang.NoClassDefFoundError: scala/collection/IterableOnce
	at za.co.absa.spline.harvester.LineageHarvester$.traverseAndCollect$2(LineageHarvester.scala:160)
	at za.co.absa.spline.harvester.LineageHarvester$.za$co$absa$spline$harvester$LineageHarvester$$getExecutedReadWriteMetrics(LineageHarvester.scala:166)
	at za.co.absa.spline.harvester.LineageHarvester$$anonfun$1.apply(LineageHarvester.scala:54)
	at za.co.absa.spline.harvester.LineageHarvester$$anonfun$1.apply(LineageHarvester.scala:54)
	at scala.Option.map(Option.scala:146)
	at za.co.absa.spline.harvester.LineageHarvester.harvest(LineageHarvester.scala:54)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:41)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener$$anonfun$onSuccess$1.apply(SplineQueryExecutionListener.scala:37)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener$$anonfun$onSuccess$1.apply(SplineQueryExecutionListener.scala:37)
	at scala.Option.foreach(Option.scala:257)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:37)
	at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1$$anonfun$apply$mcV$sp$1.apply(QueryExecutionListener.scala:124)
	at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1$$anonfun$apply$mcV$sp$1.apply(QueryExecutionListener.scala:123)
	at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$org$apache$spark$sql$util$ExecutionListenerManager$$withErrorHandling$1.apply(QueryExecutionListener.scala:145)
...
at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:639)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:485)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:597)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:390)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cerveada** [comment]
Hello, 
are you using the same Scala versions for all Scala libraries? This looks like Scala version mismatch.

**Comment by dKiwi** [comment]
That was the case indeed. Thank you.
