### ISSUE TITLE
java.lang.NumberFormatException: Not a version: 9

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#598]
_Originally posted by @Qurashetufail in https://github.com/AbsaOSS/spline/issues/588#issuecomment-587104712_

I tried the code with oracle today. The code is now throwing a new error.
```
   [java] Exception in thread "main" java.lang.ExceptionInInitializerError
     [java]     at za.co.absa.spline.harvester.json.ShortTypeHintForSpline03ModelSupport$class.formats(ShortTypeHintForSpline03ModelSupport.scala:28)
     [java]     at za.co.absa.spline.harvester.json.HarvesterJsonSerDe$.za$co$absa$spline$common$json$format$NoEmptyValuesSupport$$super$formats(HarvesterJsonSerDe.scala:22)
     [java]     at za.co.absa.spline.common.json.format.NoEmptyValuesSupport$class.formats(NoEmptyValuesSupport.scala:24)
     [java]     at za.co.absa.spline.harvester.json.HarvesterJsonSerDe$.za$co$absa$spline$common$json$format$JavaTypesSupport$$super$formats(HarvesterJsonSerDe.scala:22)
     [java]     at za.co.absa.spline.common.json.format.JavaTypesSupport$class.formats(JavaTypesSupport.scala:23)
     [java]     at za.co.absa.spline.harvester.json.HarvesterJsonSerDe$.formats(HarvesterJsonSerDe.scala:22)
     [java]     at za.co.absa.spline.common.json.AbstractJsonSerDe$class.$init$(AbstractJsonSerDe.scala:30)
     [java]     at za.co.absa.spline.harvester.json.HarvesterJsonSerDe$.<init>(HarvesterJsonSerDe.scala:22)
     [java]     at za.co.absa.spline.harvester.json.HarvesterJsonSerDe$.<clinit>(HarvesterJsonSerDe.scala)
     [java]     at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher.send(HttpLineageDispatcher.scala:41)
     [java]     at za.co.absa.spline.harvester.QueryExecutionEventHandler$$anonfun$onSuccess$1.apply(QueryExecutionEventHandler.scala:45)
     [java]     at za.co.absa.spline.harvester.QueryExecutionEventHandler$$anonfun$onSuccess$1.apply(QueryExecutionEventHandler.scala:43)
     [java]     at scala.Option.foreach(Option.scala:257)
     [java]     at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:43)
     [java]     at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener$$anonfun$onSuccess$1.apply(SplineQueryExecutionListener.scala:37)
     [java]     at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener$$anonfun$onSuccess$1.apply(SplineQueryExecutionListener.scala:37)
     [java]     at scala.Option.foreach(Option.scala:257)
     [java]     at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:37)
     [java]     at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1$$anonfun$apply$mcV$sp$1.apply(QueryExecutionListener.scala:114)
     [java]     at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1$$anonfun$apply$mcV$sp$1.apply(QueryExecutionListener.scala:113)
     [java]     at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$org$apache$spark$sql$util$ExecutionListenerManager$$withErrorHandling$1.apply(QueryExecutionListener.scala:135)
     [java]     at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$org$apache$spark$sql$util$ExecutionListenerManager$$withErrorHandling$1.apply(QueryExecutionListener.scala:133)
     [java]     at scala.collection.immutable.List.foreach(List.scala:392)
     [java]     at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
     [java]     at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
     [java]     at org.apache.spark.sql.util.ExecutionListenerManager.org$apache$spark$sql$util$ExecutionListenerManager$$withErrorHandling(QueryExecutionListener.scala:133)
     [java]     at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1.apply$mcV$sp(QueryExecutionListener.scala:113)
     [java]     at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1.apply(QueryExecutionListener.scala:113)
     [java]     at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1.apply(QueryExecutionListener.scala:113)
     [java]     at org.apache.spark.sql.util.ExecutionListenerManager.readLock(QueryExecutionListener.scala:146)
     [java]     at org.apache.spark.sql.util.ExecutionListenerManager.onSuccess(QueryExecutionListener.scala:112)
     [java]     at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:611)
     [java]     at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:233)
     [java]     at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:217)
     [java]     at org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:508)
     [java]     at za.co.absa.spline.example.batch.CumminsJob1DB$.delayedEndpoint$za$co$absa$spline$example$batch$CumminsJob1DB$1(CumminsJob1DB.scala:250)
     [java]     at za.co.absa.spline.example.batch.CumminsJob1DB$delayedInit$body.apply(CumminsJob1DB.scala:19)
     [java]     at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
     [java]     at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
     [java]     at scala.App$$anonfun$main$1.apply(App.scala:76)
     [java]     at scala.App$$anonfun$main$1.apply(App.scala:76)
     [java]     at scala.collection.immutable.List.foreach(List.scala:392)
     [java]     at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
     [java]     at scala.App$class.main(App.scala:76)
     [java]     at za.co.absa.spline.example.SparkApp.main(SparkApp.scala:27)
     [java]     at za.co.absa.spline.example.batch.CumminsJob1DB.main(CumminsJob1DB.scala)
     [java] Caused by: java.lang.NumberFormatException: Not a version: 9
     [java]     at scala.util.PropertiesTrait$class.parts$1(Properties.scala:184)
     [java]     at scala.util.PropertiesTrait$class.isJavaAtLeast(Properties.scala:187)
     [java]     at scala.util.Properties$.isJavaAtLeast(Properties.scala:17)
     [java]     at scala.tools.util.PathResolverBase$Calculated$.javaBootClasspath(PathResolver.scala:276)
     [java]     at scala.tools.util.PathResolverBase$Calculated$.basis(PathResolver.scala:283)
     [java]     at scala.tools.util.PathResolverBase$Calculated$.containers$lzycompute(PathResolver.scala:293)
     [java]     at scala.tools.util.PathResolverBase$Calculated$.containers(PathResolver.scala:293)
     [java]     at scala.tools.util.PathResolverBase.containers(PathResolver.scala:309)
     [java]     at scala.tools.util.PathResolver.computeResult(PathResolver.scala:341)
     [java]     at scala.tools.util.PathResolver.computeResult(PathResolver.scala:332)
     [java]     at scala.tools.util.PathResolverBase.result(PathResolver.scala:314)
     [java]     at scala.tools.nsc.backend.JavaPlatform$class.classPath(JavaPlatform.scala:28)
     [java]     at scala.tools.nsc.Global$GlobalPlatform.classPath(Global.scala:115)
     [java]     at scala.tools.nsc.Global.scala$tools$nsc$Global$$recursiveClassPath(Global.scala:131)
     [java]     at scala.tools.nsc.Global.classPath(Global.scala:128)
     [java]     at scala.tools.nsc.backend.jvm.BTypesFromSymbols.<init>(BTypesFromSymbols.scala:39)
     [java]     at scala.tools.nsc.backend.jvm.BCodeIdiomatic.<init>(BCodeIdiomatic.scala:24)
     [java]     at scala.tools.nsc.backend.jvm.BCodeHelpers.<init>(BCodeHelpers.scala:23)
     [java]     at scala.tools.nsc.backend.jvm.BCodeSkelBuilder.<init>(BCodeSkelBuilder.scala:25)
     [java]     at scala.tools.nsc.backend.jvm.BCodeBodyBuilder.<init>(BCodeBodyBuilder.scala:25)
     [java]     at scala.tools.nsc.backend.jvm.BCodeSyncAndTry.<init>(BCodeSyncAndTry.scala:21)
     [java]     at scala.tools.nsc.backend.jvm.GenBCode.<init>(GenBCode.scala:47)
     [java]     at scala.tools.nsc.Global$genBCode$.<init>(Global.scala:675)
     [java]     at scala.tools.nsc.Global.genBCode$lzycompute(Global.scala:671)
     [java]     at scala.tools.nsc.Global.genBCode(Global.scala:671)
     [java]     at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.serialVUID(GenASM.scala:1240)
     [java]     at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genClass(GenASM.scala:1329)
     [java]     at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.emitFor$1(GenASM.scala:198)
     [java]     at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.run(GenASM.scala:204)
     [java]     at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1528)
     [java]     at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1513)
     [java]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.wrapInPackageAndCompile(ToolBoxFactory.scala:197)
     [java]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.compile(ToolBoxFactory.scala:252)
     [java]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$$anonfun$compile$2.apply(ToolBoxFactory.scala:429)
     [java]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$$anonfun$compile$2.apply(ToolBoxFactory.scala:422)
     [java]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.liftedTree2$1(ToolBoxFactory.scala:355)
     [java]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.apply(ToolBoxFactory.scala:355)
     [java]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.compile(ToolBoxFactory.scala:422)
     [java]     at za.co.absa.spline.common.ReflectionUtils$.compile(ReflectionUtils.scala:45)
     [java]     at za.co.absa.spline.harvester.json.ShortTypeHintForSpline03ModelSupport$.<init>(ShortTypeHintForSpline03ModelSupport.scala:39)
     [java]     at za.co.absa.spline.harvester.json.ShortTypeHintForSpline03ModelSupport$.<clinit>(ShortTypeHintForSpline03ModelSupport.scala)
     [java]     ... 46 more
     [java] 20/02/17 23:01:58 INFO SparkContext: Invoking stop() from shutdown hook
     [java] 20/02/17 23:01:58 INFO SparkUI: Stopped Spark web UI at http://169.254.103.167:4040
     [java] 20/02/17 23:01:58 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
     [java] 20/02/17 23:01:59 INFO MemoryStore: MemoryStore cleared
     [java] 20/02/17 23:01:59 INFO BlockManager: BlockManager stopped
     [java] 20/02/17 23:01:59 INFO BlockManagerMaster: BlockManagerMaster stopped
     [java] 20/02/17 23:01:59 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
     [java] 20/02/17 23:01:59 INFO SparkContext: Successfully stopped SparkContext
     [java] 20/02/17 23:01:59 INFO ShutdownHookManager: Shutdown hook called
     [java] 20/02/17 23:01:59 INFO ShutdownHookManager: Deleting directory 
``` 
Is the compatibility issue of scala and spark or it is the Spline error? Please let me know if you need any further details from my side.
The Java version details  I am using is mentioned below
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

Thanks,
Tufail

**Comment by wajda** [comment]
# Explanation
It's **not** a Spine issue! The problem is laying between _Scala_ and the user's runtime.

The error is caused by using different versions of `scala-library` and `scala-compiler` artifacts. Namely `scala-library < 2.11.12` and `scala-compiler >= 2.11.12`.

The original issue (https://github.com/scala/bug/issues/9750) has been fixed in `Scala 2.12` and backported to `Scala 2.11.12`.

# Fix

Upgrade to _Scala 2.11.12+_
