### ISSUE TITLE
Cobol connector support (Cobrix)

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#639]
https://github.com/AbsaOSS/cobrix

```
java.lang.RuntimeException: Relation is not supported: za.co.absa.cobrix.spark.cobol.source.CobolRelation@30ce78e3
        at scala.sys.package$.error(package.scala:27)
        at za.co.absa.spline.harvester.builder.read.ReadCommandExtractor$$anonfun$asReadCommand$1.applyOrElse(ReadCommandExtractor.scala:110)
        at za.co.absa.spline.harvester.builder.read.ReadCommandExtractor$$anonfun$asReadCommand$1.applyOrElse(ReadCommandExtractor.scala:49)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
        at scala.PartialFunction$.condOpt(PartialFunction.scala:286)
        at za.co.absa.spline.harvester.builder.read.ReadCommandExtractor.asReadCommand(ReadCommandExtractor.scala:49)
        at za.co.absa.spline.harvester.LineageHarvester.za$co$absa$spline$harvester$LineageHarvester$$createOperationBuilder(LineageHarvester.scala:144)
- SparkCobolApp$
        at za.co.absa.spline.harvester.LineageHarvester$$anonfun$6.apply(LineageHarvester.scala:121)
        at za.co.absa.spline.harvester.LineageHarvester$$anonfun$6.apply(LineageHarvester.scala:121)
        at scala.Option.getOrElse(Option.scala:121)
        at za.co.absa.spline.harvester.LineageHarvester.traverseAndCollect$1(LineageHarvester.scala:121)
        at za.co.absa.spline.harvester.LineageHarvester.za$co$absa$spline$harvester$LineageHarvester$$createOperationBuildersRecursively(LineageHarvester.scala:140)
        at za.co.absa.spline.harvester.LineageHarvester$$anonfun$harvest$1.apply(LineageHarvester.scala:72)
        at za.co.absa.spline.harvester.LineageHarvester$$anonfun$harvest$1.apply(LineageHarvester.scala:70)
        at scala.Option.flatMap(Option.scala:171)
        at za.co.absa.spline.harvester.LineageHarvester.harvest(LineageHarvester.scala:70)
        at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:40)
        at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener$$anonfun$onSuccess$1.apply(SplineQueryExecutionListener.scala:37)
        at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener$$anonfun$onSuccess$1.apply(SplineQueryExecutionListener.scala:37)
        at scala.Option.foreach(Option.scala:257)
        at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:37)
        at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1$$anonfun$apply$mcV$sp$1.apply(QueryExecutionListener.scala:124)
        at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1$$anonfun$apply$mcV$sp$1.apply(QueryExecutionListener.scala:123)
        at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$org$apache$spark$sql$util$ExecutionListenerManager$$withErrorHandling$1.apply(QueryExecutionListener.scala:145)
```

**Comment by wajda** [comment]
CC @yruslan, @Zejnilovic

**Comment by yruslan** [comment]
This is very interesting. Thanks!

Are you considering adding support for Cobrix (`spark-cobol`) specifically or you want Spline to be able to support arbitrary custom relation types?

**Comment by wajda** [comment]
It would be awesome if could do it in a generic way, but unfortunately Spark API doesn't provide any generic way to determine the read/write destination. That's why we have to support every type of relation specifically.
