### ISSUE TITLE
Run Build Tool with Authentication to Arrango DB

### ISSUE THREAD

**Issue by agrajm** [AbsaOSS/spline#666]
## Background
I'm able to run the admin tool successfully when arrango db is run in an unsecured fashion without any password
`
java -jar admin-0.5.1.jar db-init arangodb://localhost/spline
`

## Question
How to run the admin tool when arrango db is setup with password authentication - without specifying a password, unsurprisingly it fails with

```
Exception in thread "main" java.util.concurrent.CompletionException: com.arangodb.ArangoDBException: Response: 401, Error: 11 - not authorized to execute this request
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
        at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925)
        at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:913)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
        at com.arangodb.async.internal.velocystream.VstCommunicationAsync.lambda$execute$0(VstCommunicationAsync.java:66)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
        at com.arangodb.async.internal.velocystream.VstConnectionAsync.lambda$write$0(VstConnectionAsync.java:48)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.arangodb.internal.velocystream.internal.MessageStore.consume(MessageStore.java:62)
        at com.arangodb.internal.velocystream.internal.ChunkStore.checkCompleteness(ChunkStore.java:65)
        at com.arangodb.internal.velocystream.internal.ChunkStore.checkCompleteness(ChunkStore.java:59)
        at com.arangodb.internal.velocystream.internal.VstConnection.lambda$open$0(VstConnection.java:151)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.arangodb.ArangoDBException: Response: 401, Error: 11 - not authorized to execute this request
        ... 15 more 
```

How to specify the password for arrango db when running this tool ?

**Comment by cerveada** [comment]
Run `java -jar admin-0.5.1.jar --help` to get admin's help. The output may differ slightly depending on the spline version. But this is the output for version 0.5.0:
```
Spline Admin Command Line Interface 0.5.0-SNAPSHOT
Usage: Spline Admin CLI [db-init|db-upgrade] [options] <args>...

  --help                   prints this usage text
Command: db-init [options] <db_url>
Initialize Spline database
  -t, --timeout <value>    Timeout in format `<length><unit>` or `Inf` for infinity. Default is 1 minute
  -k, --insecure           Allow insecure server connections when using SSL; disallowed by default
  <db_url>                 ArangoDB connection string in the format: arangodb|arangodbs://[user[:password]@]host[:port]/database
  -f, --force              Re-create the database if one already exists
  -s, --skip               Skip existing database. Don't throw error, just end
Command: db-upgrade [options] <db_url>
Upgrade Spline database
  -t, --timeout <value>    Timeout in format `<length><unit>` or `Inf` for infinity. Default is 1 minute
  -k, --insecure           Allow insecure server connections when using SSL; disallowed by default
  <db_url>                 ArangoDB connection string in the format: arangodb|arangodbs://[user[:password]@]host[:port]/database
```

From this you can find that the pasword is part of the url   `arangodb|arangodbs://[user[:password]@]host[:port]/database`

**Comment by wajda** [comment]
The point here (if I get it right) is to avoid putting the password into the command line, but type it in on prompt.
That is currently not supported, but I think we should add this feature.

**Comment by agrajm** [comment]
Thank you folks. Closing as I'm able to use the password on command line, which satisfies my requirements as of now. Definitely having the ability to specify on prompt would be better though.
