### ISSUE TITLE
Spline fails to report lineage when plan contains Scala lambda

### ISSUE THREAD

**Issue by DaimonPl** [AbsaOSS/spline#681]
Checked on spline agent 0.5.1 with Scala 2.12, Spark 2.4.5

Code uses Scala Dataframe/Dataset transformation including lambda expressions it fails with following error:

`WARN ExecutionListenerManager: Error executing query execution listener
java.lang.AssertionError: assertion failed: no symbol could be loaded from class a.b.c.MyClass$$Lambda$4843/566774261 in package c with name MyClass$$Lambda$4843/566774261 and classloader sun.misc.Launcher$AppClassLoader@18b4aac2
	at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:184)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala1(JavaMirrors.scala:1061)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$classToScala$1(JavaMirrors.scala:1019)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$toScala$1(JavaMirrors.scala:130)
	at scala.reflect.runtime.TwoWayCaches$TwoWayCache.$anonfun$toScala$1(TwoWayCaches.scala:50)
	at scala.reflect.runtime.TwoWayCaches$TwoWayCache.toScala(TwoWayCaches.scala:46)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.toScala(JavaMirrors.scala:128)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala(JavaMirrors.scala:1019)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.classSymbol(JavaMirrors.scala:231)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.classSymbol(JavaMirrors.scala:68)
	at za.co.absa.commons.reflect.ReflectionUtils$ModuleClassSymbolExtractor$.unapply(ReflectionUtils.scala:33)
	at za.co.absa.spline.harvester.converter.ValueDecomposer$$anonfun$$nestedInanonfun$handler$2$1.applyOrElse(ValueDecomposer.scala:52)
	at za.co.absa.spline.harvester.converter.ValueDecomposer$$anonfun$$nestedInanonfun$handler$2$1.applyOrElse(ValueDecomposer.scala:44)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at za.co.absa.spline.harvester.converter.OperationParamsConverter$$anonfun$$nestedInanonfun$renderer$1$1.applyOrElse(OperationParamsConverter.scala:35)
	at za.co.absa.spline.harvester.converter.OperationParamsConverter$$anonfun$$nestedInanonfun$renderer$1$1.applyOrElse(OperationParamsConverter.scala:35)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at za.co.absa.spline.harvester.converter.ValueDecomposer.$anonfun$recursion$1(ValueDecomposer.scala:39)
	at za.co.absa.spline.harvester.converter.OperationParamsConverter.$anonfun$convert$6(OperationParamsConverter.scala:59)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:827)`

**Comment by DaimonPl** [comment]
Works fine on Scala 2.11

**Comment by cerveada** [comment]
@wajda Do you think it's absa.commons problem or is it Spline problem?

**Comment by wajda** [comment]
@DaimonPl can you provide a code example to reproduce the issue?

**Comment by wajda** [comment]
Moving the issue to the [spline-spark-agent](/AbsaOSS/spline-spark-agent) project.
