### ISSUE TITLE
Spline UI 0.5.1 error: Http failure response for http://localhost:8080/consumer/execution-events

### ISSUE THREAD

**Issue by wernerstinckens** [AbsaOSS/spline#692]
## Describe the bug
When running the Spline UI in a docker container (as explained in the docs), we get the following error in the UI:

> ERROR
> Server returned code: 0, error message is: Http failure response for http://localhost:8080/consumer/execution-events: 0 Unknown Error 

When calling the URL (http://localhost:8080/consumer/execution-events) directly in a browser, it does return data though.

ArangoDB collections recorded data, so the server part seems to work, except for the server/UI interaction.

## Versions
Spline Server 0.5.1
Spline UI 0.5.1
Spline Agent 0.5.3
Spark 2.4.5
Scala 2.11

## Components State
- [x] ArangoDB running without errors
- [x] ArangoDB spline database initialized
- Rest Gateway running and
  - [x] connects to ArangoDB
  - [x] there are no errors in logs
- Spline UI running and
  - [ ] connects to Rest Gateway consumer
  - [x] there are no errors in logs

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. deploy Arangodb in docker (& initialize spline db)
2. deploy Spline Server in docker as in the docs
3. deploy Spline UI in docker as in the docs
containers run on a single CentOs 7 host
4. open the UI URL (http://...:9090)

## Expected behaviour
I expect to see the recorded data, but get 'error unknown' instead

## Screenshots
![image](https://user-images.githubusercontent.com/45622961/83650126-46495d00-a5b8-11ea-9fa4-19cc98f07844.png)

## Desktop (please complete the following information):
- OS: Windows 10
- Browser [chrome, firefox,edge]

**Comment by wajda** [comment]
What does the developer console says? Is there anything in the "Console" tab, or "XHR" tab?

**Comment by wernerstinckens** [comment]
I am trying in the same browser(firefox).
So I opened up de dev console and indeed, at the same time as the error I get a CORS request error.

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/consumer/execution-events?sortOrder=desc&sortField=timestamp&pageNum=1&asAtTime=1591250259634. (Reason: CORS request did not succeed)

I guess I have to talk to our network admin.
Tnx!

**Comment by wernerstinckens** [comment]
I started the UI container with the IP-address of the host instead of localhost (I want to open the web application on any PC in our network) and this solves the issue.
Tnx for helping me out!

**Comment by nehapriyathakur** [comment]
I am setting up a project with below dependencies on Spline with Spark
```
za.co.absa.spline.agent.spark
agent-core_2.11
0.5.1


org.scala-lang
scala-library
2.11.8



org.apache.spark
spark-core_2.11
2.4.5

    </dependency>
    <!-- https://mvnrepository.com/artifact/org.apache.spark/spark-sql_2.11 -->
    <dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-sql_2.11</artifactId>
        <version>2.4.5</version>

    </dependency>
    <!-- https://mvnrepository.com/artifact/org.apache.spark/spark-streaming_2.11 -->
    <dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-sql-kafka-0-10_2.11</artifactId>
        <version>2.4.5</version>
    </dependency>
```
Above is how my pom.xml look like.

The code is changed to add below lines
```java
import za.co.absa.spline.harvester.SparkLineageInitializer;

SparkLineageInitializer.SparkSessionWrapper sessionWrapper = new SparkLineageInitializer.SparkSessionWrapper(session);
sessionWrapper.enableLineageTracking(sessionWrapper.enableLineageTracking$default$1());
```
I am submitting the spark code but getting the error
```
Exception in thread "main" java.lang.NoClassDefFoundError: scala/reflect/io/JavaToolsPlatformArchive
at scala.tools.util.PathResolverBase.Calculated$lzycompute(PathResolver.scala:238)
at scala.tools.util.PathResolverBase.Calculated(PathResolver.scala:238)
at scala.tools.util.PathResolverBase.containers(PathResolver.scala:309)
at scala.tools.util.PathResolver.computeResult(PathResolver.scala:341)
at scala.tools.util.PathResolver.computeResult(PathResolver.scala:332)
at scala.tools.util.PathResolverBase.result(PathResolver.scala:314)
at scala.tools.nsc.backend.JavaPlatform$class.classPath(JavaPlatform.scala:28)
at scala.tools.nsc.Global$GlobalPlatform.classPath(Global.scala:115)
at scala.tools.nsc.Global.scala$tools$nsc$Global$$recursiveClassPath(Global.scala:131)
at scala.tools.nsc.Global.classPath(Global.scala:128)
at scala.tools.nsc.backend.jvm.BTypesFromSymbols.(BTypesFromSymbols.scala:39)
at scala.tools.nsc.backend.jvm.BCodeIdiomatic.(BCodeIdiomatic.scala:24)
at scala.tools.nsc.backend.jvm.BCodeHelpers.(BCodeHelpers.scala:23)
at scala.tools.nsc.backend.jvm.BCodeSkelBuilder.(BCodeSkelBuilder.scala:25)
at scala.tools.nsc.backend.jvm.BCodeBodyBuilder.(BCodeBodyBuilder.scala:25)
at scala.tools.nsc.backend.jvm.BCodeSyncAndTry.(BCodeSyncAndTry.scala:21)
at scala.tools.nsc.backend.jvm.GenBCode.(GenBCode.scala:47)
at scala.tools.nsc.Global$genBCode$.(Global.scala:675)
at scala.tools.nsc.Global.genBCode$lzycompute(Global.scala:671)
at scala.tools.nsc.Global.genBCode(Global.scala:671)
at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.serialVUID(GenASM.scala:1240)
at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genClass(GenASM.scala:1329)
at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.emitFor$1(GenASM.scala:198)
at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.run(GenASM.scala:204)
at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1528)
at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1513)
at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.wrapInPackageAndCompile(ToolBoxFactory.scala:197)
at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.compile(ToolBoxFactory.scala:252)
at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$$anonfun$compile$2.apply(ToolBoxFactory.scala:429)
at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$$anonfun$compile$2.apply(ToolBoxFactory.scala:422)
at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.liftedTree2$1(ToolBoxFactory.scala:355)
at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.apply(ToolBoxFactory.scala:355)
at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.compile(ToolBoxFactory.scala:422)
at za.co.absa.commons.reflect.ReflectionUtils$.compile(ReflectionUtils.scala:41)
at za.co.absa.spline.harvester.json.HarvesterJsonSerDe$.(HarvesterJsonSerDe.scala:25)
at za.co.absa.spline.harvester.json.HarvesterJsonSerDe$.(HarvesterJsonSerDe.scala)
at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher.send(HttpLineageDispatcher.scala:161)
at za.co.absa.spline.harvester.QueryExecutionEventHandler$$anonfun$onSuccess$1.apply(QueryExecutionEventHandler.scala:43)
at za.co.absa.spline.harvester.QueryExecutionEventHandler$$anonfun$onSuccess$1.apply(QueryExecutionEventHandler.scala:41)
at scala.Option.foreach(Option.scala:257)
at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:41)
at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener$$anonfun$onSuccess$1.apply(SplineQueryExecutionListener.scala:37)
at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener$$anonfun$onSuccess$1.apply(SplineQueryExecutionListener.scala:37)
at scala.Option.foreach(Option.scala:257)
at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:37)
at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1$$anonfun$apply$mcV$sp$1.apply(QueryExecutionListener.scala:127)
at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1$$anonfun$apply$mcV$sp$1.apply(QueryExecutionListener.scala:126)
at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$org$apache$spark$sql$util$ExecutionListenerManager$$withErrorHandling$1.apply(QueryExecutionListener.scala:148)
at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$org$apache$spark$sql$util$ExecutionListenerManager$$withErrorHandling$1.apply(QueryExecutionListener.scala:146)
at scala.collection.immutable.List.foreach(List.scala:381)
at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
at org.apache.spark.sql.util.ExecutionListenerManager.org$apache$spark$sql$util$ExecutionListenerManager$$withErrorHandling(QueryExecutionListener.scala:146)
at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1.apply$mcV$sp(QueryExecutionListener.scala:126)
at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1.apply(QueryExecutionListener.scala:126)
at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1.apply(QueryExecutionListener.scala:126)
at org.apache.spark.sql.util.ExecutionListenerManager.readLock(QueryExecutionListener.scala:159)
at org.apache.spark.sql.util.ExecutionListenerManager.onSuccess(QueryExecutionListener.scala:125)
at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:678)
at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:285)
at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:229)
at HousePriceSolution.main(HousePriceSolution.java:43)
Caused by: java.lang.ClassNotFoundException: scala.reflect.io.JavaToolsPlatformArchive
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
... 63 more
```
Process finished with exit code 1

Is spline not compatible with spark 2.4.5 version? If that's the case, could anyone suggest on the correct dependencies to be added?

Thanks in advance!

**Comment by wajda** [comment]
@nehapriyathakur,
As I understand you posted your question accidentally here, as this ticket is closed and has nothing in common with yours.
Regarding your question, please make sure you are using an agent jar compiles against the same Scala version that your Spark is using. The error message suggests that you might be using incompatible Scala version.

**Comment by wajda** [comment]
Should you have more questions please open a separate ticket
