### ISSUE TITLE
While configuring Arangodb connection URL - getting error "com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream"

### ISSUE THREAD

**Issue by ankit302** [AbsaOSS/spline#743]
## Background 
We are trying to setup Spline on Azure Kubernetes environment by following the spline documentation; [Spline docs](https://absaoss.github.io/spline/).

Below is the deployment /configuration we have used;

Spline Deployment.yaml:
```
> apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: spline
  name: spline-rest
  namespace: dataservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spline
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: spline
    spec:
      containers:
      - args:
        - bash
        - -c
        - echo 'Initializing Spline DB...' && curl -O -s https://repo1.maven.org/maven2/za/co/absa/spline/admin/0.5.0/admin-0.5.0.jar
          && java -jar ./admin-0.5.0.jar db-init arangodb://root@single-server:8529/spline -s &&
          catalina.sh run
        env:
        - name: spline.database.connectionUrl
          value: arangodb://root@single-server:8529/spline
        image: absaoss/spline-rest-server
        imagePullPolicy: ""
        name: spline
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
```

Spline service.yaml
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: spline
  name: spline-rest-svc
  namespace: dataservice
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 8080
  selector:
    io.kompose.service: spline
status:
  loadBalancer: {}
```

Spline crest server pod is failing with below error log:
```
8174 request.go:621] Throttling request took 1.144848754s, request: GET:https://amp-cnsdpaks-fc2a0e17.hcp.australiaeast.azmk8s.io:443/apis/networking.istio.io/v1alpha3?timeout=32s
28-Jun-2020 17:10:26.202 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.27
28-Jun-2020 17:10:26.208 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Oct 7 2019 09:57:22 UTC
28-Jun-2020 17:10:26.208 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.27.0
28-Jun-2020 17:10:26.208 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
28-Jun-2020 17:10:26.208 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.15.0-1083-azure
28-Jun-2020 17:10:26.208 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
28-Jun-2020 17:10:26.209 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-1.8.0-amazon-corretto/jre
28-Jun-2020 17:10:26.209 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_232-b09
28-Jun-2020 17:10:26.209 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Amazon.com Inc.
28-Jun-2020 17:10:26.209 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
28-Jun-2020 17:10:26.209 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
28-Jun-2020 17:10:26.210 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
28-Jun-2020 17:10:26.210 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
28-Jun-2020 17:10:26.210 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
28-Jun-2020 17:10:26.211 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
28-Jun-2020 17:10:26.211 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
28-Jun-2020 17:10:26.211 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
28-Jun-2020 17:10:26.211 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
28-Jun-2020 17:10:26.212 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
28-Jun-2020 17:10:26.212 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
28-Jun-2020 17:10:26.213 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.23] using APR version [1.6.3].
28-Jun-2020 17:10:26.214 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
28-Jun-2020 17:10:26.214 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
28-Jun-2020 17:10:26.220 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.0.2k-fips  26 Jan 2017]
28-Jun-2020 17:10:26.548 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
28-Jun-2020 17:10:26.575 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
28-Jun-2020 17:10:26.579 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [574] milliseconds
28-Jun-2020 17:10:26.598 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
28-Jun-2020 17:10:26.598 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.27]
28-Jun-2020 17:10:26.620 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
28-Jun-2020 17:10:33.662 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
17:10:33.668 [main] INFO  o.s.web.context.ContextLoader - Root WebApplicationContext: initialization started
17:10:34.271 [main] INFO  z.c.a.s.p.ArangoRepoConfig$$EnhancerBySpringCGLIB$$cd2ea4ca - Connecting to arangodb://root@single-server:8529/spline
17:10:34.554 [pool-1-thread-1] ERROR c.a.i.v.internal.VstConnection - Error on Connection connection_1593364234508_0.23333424197914
17:10:34.588 [pool-3-thread-1] ERROR c.a.i.v.internal.MessageStore - Reached the end of the stream.
java.io.IOException: Reached the end of the stream.
        at com.arangodb.internal.velocystream.internal.VstConnection.readBytesIntoBuffer(VstConnection.java:273)
        at com.arangodb.internal.velocystream.internal.VstConnection.readBytes(VstConnection.java:265)
        at com.arangodb.internal.velocystream.internal.VstConnection.readChunk(VstConnection.java:239)
        at com.arangodb.internal.velocystream.internal.VstConnection.lambda$open$0(VstConnection.java:145)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
17:10:34.589 [pool-3-thread-1] ERROR c.a.a.i.v.VstCommunicationAsync - java.io.IOException: Reached the end of the stream.
com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
        at com.arangodb.internal.velocystream.internal.MessageStore.get(MessageStore.java:71)
        at com.arangodb.async.internal.velocystream.VstConnectionAsync.lambda$write$0(VstConnectionAsync.java:48)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.arangodb.internal.velocystream.internal.MessageStore.clear(MessageStore.java:94)
        at com.arangodb.internal.velocystream.internal.VstConnection.lambda$open$0(VstConnection.java:154)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Reached the end of the stream.
        at com.arangodb.internal.velocystream.internal.VstConnection.readBytesIntoBuffer(VstConnection.java:273)
        at com.arangodb.internal.velocystream.internal.VstConnection.readBytes(VstConnection.java:265)
        at com.arangodb.internal.velocystream.internal.VstConnection.readChunk(VstConnection.java:239)
        at com.arangodb.internal.velocystream.internal.VstConnection.lambda$open$0(VstConnection.java:145)
        ... 4 common frames omitted
17:10:34.591 [main] WARN  z.c.a.s.g.r.AppInitializer$$anon$1 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'arangoRepoConfig': Invocation of init method failed; nested exception is java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
17:10:34.598 [main] WARN  o.s.b.f.s.DisposableBeanAdapter - Invocation of destroy method failed on bean with name 'arangoDatabaseFacade': java.lang.ClassCastException: com.arangodb.async.internal.velocystream.VstConnectionAsync cannot be cast to com.arangodb.internal.velocystream.internal.VstConnectionSync
17:10:34.608 [main] ERROR o.s.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'arangoRepoConfig': Invocation of init method failed; nested exception is java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4683)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5146)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1849)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:344)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:475)
Caused by: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
        at za.co.absa.spline.persistence.ArangoRepoConfig.afterPropertiesSet(ArangoRepoConfig.scala:36)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
        ... 53 common frames omitted
Caused by: com.arangodb.ArangoDBException: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
        at com.arangodb.async.internal.velocystream.VstCommunicationAsync.authenticate(VstCommunicationAsync.java:107)
        at com.arangodb.async.internal.velocystream.VstCommunicationAsync.authenticate(VstCommunicationAsync.java:44)
        at com.arangodb.internal.velocystream.VstCommunication.connect(VstCommunication.java:90)
        at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:123)
        at com.arangodb.async.internal.ArangoExecutorAsync.lambda$execute$2(ArangoExecutorAsync.java:69)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
        at com.arangodb.async.internal.velocystream.VstCommunicationAsync.authenticate(VstCommunicationAsync.java:105)
        ... 10 common frames omitted
Caused by: com.arangodb.ArangoDBException: java.io.IOException: Reached the end of the stream.
        at com.arangodb.internal.velocystream.internal.MessageStore.get(MessageStore.java:71)
        at com.arangodb.async.internal.velocystream.VstConnectionAsync.lambda$write$0(VstConnectionAsync.java:48)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.arangodb.internal.velocystream.internal.MessageStore.clear(MessageStore.java:94)
        at com.arangodb.internal.velocystream.internal.VstConnection.lambda$open$0(VstConnection.java:154)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 common frames omitted
C**aused by: java.io.IOException: Reached the end of the stream.
        at com.arangodb.internal.velocystream.internal.VstConnection.readBytesIntoBuffer(VstConnection.java:273)**
        at com.arangodb.internal.velocystream.internal.VstConnection.readBytes(VstConnection.java:265)
        at com.arangodb.internal.velocystream.internal.VstConnection.readChunk(VstConnection.java:239)
        at com.arangodb.internal.velocystream.internal.VstConnection.lambda$open$0(VstConnection.java:145)
        ... 4 common frames omitted
28-Jun-2020 17:10:34.609 **SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
28-Jun-2020 17:10:34.618 SEVERE [main] org.apache.catalina.core.S**tandardContext.startInternal Context [] startup failed due to previous errors
28-Jun-2020 17:10:34.632 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [pool-1-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
28-Jun-2020 17:10:34.642 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [8,022] ms
28-Jun-2020 17:10:34.645 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
28-Jun-2020 17:10:34.670 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
28-Jun-2020 17:10:34.703 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [8,123] milliseconds
```

Any suggestion why we are getting this issue.

**Comment by wajda** [comment]
Please check your ArangoDB setup.
Also try to google the error message. This is one of the references -  https://github.com/arangodb/arangodb-java-driver/issues/221

**Comment by ankit302** [comment]
Hi @wajda ,

I was able to fix this issue, 
now it's failing while accessing spline WEBUI.


Spline UI Deployment.yaml:-

kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: spline-ui
  namespace: dataservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: ui
    spec:
      containers:
      - env:
        - name: CATALINA_OPTS
          value: -Dsecurerandom.source=file:/dev/./urandom -Djava.security.egd=file:/dev/./urandom
        - name: spline.consumer.url
          value: http://spline:9090/consumer
        image: 'absaoss/spline-web-client'
        imagePullPolicy: ""
        name: ui
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}



Getting error;
"ERROR
Server returned code: 0. Http failure response for http://spline:9090/consumer/execution-events"

![Capture](https://user-images.githubusercontent.com/28657492/86007563-36952b00-ba35-11ea-85a0-738a9ac918eb.PNG)

Can you please tell what i'm missing in configuration.

**Comment by wajda** [comment]
Response code `0` means `no connection`
Make sure http://spline:9090/consumer/execution-events is accessible

**Comment by ankit302** [comment]
hi @wajda , do you any issue with passing env for;

name: spline.consumer.url
value: http://spline:9090/consumer

DO you have any idea , how it supposed to be configured in K8s, below is my service config.

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: spline
  name: spline
  namespace: dataservice
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 8080
  selector:
    io.kompose.service: spline
status:
  loadBalancer: {}



apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: spline-ui
  namespace: dataservice
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: ui
status:
  loadBalancer: {}

**Comment by wajda** [comment]
I believe your config is fine. Just make sure that the URL you pass to the `spline.consumer.url` is visible from the host on which you access Spline UI. This URL isn't accessed from the server, but directly from the client browser.
