### ISSUE TITLE
VstConnectionAsync ClassCastException in ArangoDB Java Driver

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#850]
See: https://github.com/arangodb/arangodb-java-driver-async/issues/21

The issue still occurs, seemingly non-deterministically.
The driver version: `com.arangodb:arangodb-java-driver:6.9.0`
Connection string: `arangodbs://localhost:8530,localhost:8530/spline-dev-new`

A workarounds has been placed earlier for other use-cases: fb7b507632975dbfa6b652f90bec76958a232e15
As it turned our it also sometimes occurs in the warmed up application, in the Consumer API module.
The workarounds needs be applied globally for the application.

Logs:

1.
```
19:31:28.316 [http-nio-8080-exec-6] ERROR za.co.absa.commons.error.ErrorRef - ERROR_ID [ed5d0f16-6c3b-42f8-9e99-982a86944c08]
za.co.absa.spline.persistence.DatabaseException: Query execution failed: 
================================================================================
...
workName), @searchTerm)
            OR CONTAINS(LOWER(ee.execPlanDetails.applicationName), @searchTerm)
            OR CONTAINS(LOWER(ee.extra.appId), @searchTerm)
...
================================================================================
	at za.co.absa.spline.persistence.ArangoImplicits$ArangoDatabaseAsyncScalaWrapper$$anonfun$queryAs$1.applyOrElse(ArangoImplicits.scala:91)
	at za.co.absa.spline.persistence.ArangoImplicits$ArangoDatabaseAsyncScalaWrapper$$anonfun$queryAs$1.applyOrElse(ArangoImplicits.scala:88)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at scala.util.Failure.recover(Try.scala:234)
	at scala.concurrent.Future.$anonfun$recover$1(Future.scala:395)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassCastException: class com.arangodb.async.internal.velocystream.VstConnectionAsync cannot be cast to class com.arangodb.internal.velocystream.internal.VstConnectionSync (com.arangodb.async.internal.velocystream.VstConnectionAsync and com.arangodb.internal.velocystream.internal.VstConnectionSync are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @62dc1d21)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:40)
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:138)
	at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:46)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)
	at com.arangodb.internal.net.ExtendedHostResolver.resolveFromServer(ExtendedHostResolver.java:127)
	at com.arangodb.internal.net.ExtendedHostResolver.resolve(ExtendedHostResolver.java:85)
	at com.arangodb.internal.net.FallbackHostHandler.confirm(FallbackHostHandler.java:80)
	at com.arangodb.internal.net.DirtyReadHostHandler.confirm(DirtyReadHostHandler.java:70)
	at com.arangodb.internal.velocystream.VstCommunication.connect(VstCommunication.java:97)
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:137)
	at com.arangodb.async.internal.ArangoExecutorAsync.lambda$execute$2(ArangoExecutorAsync.java:69)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

2.
```
21:30:03.914 [http-nio-8080-exec-7] ERROR za.co.absa.commons.error.ErrorRef - ERROR_ID [6241206f-9801-4531-8af7-340406b2df4f]
za.co.absa.spline.persistence.DatabaseException: Query execution failed: 
================================================================================
...
FOR a IN 1
            OUTBOUND sid consistsOf
            RETURN DISTINCT {
                "id"   : a._key,
                "name" : a.name,
                "dataTypeId" : a.dataType
            }
)

LET inputs = FLATTEN(
    FOR op IN ops
        FILTER op.type == "Read"
        RETURN op.inputSources[* RETURN {
            "source"    : CURRENT,
            "sourceType": op.extra.sourceType
        }]
    )

LE
...
================================================================================
	at za.co.absa.spline.persistence.ArangoImplicits$ArangoDatabaseAsyncScalaWrapper$$anonfun$queryAs$1.applyOrElse(ArangoImplicits.scala:91)
	at za.co.absa.spline.persistence.ArangoImplicits$ArangoDatabaseAsyncScalaWrapper$$anonfun$queryAs$1.applyOrElse(ArangoImplicits.scala:88)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at scala.util.Failure.recover(Try.scala:234)
	at scala.concurrent.Future.$anonfun$recover$1(Future.scala:395)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.ClassCastException: class com.arangodb.async.internal.velocystream.VstConnectionAsync cannot be cast to class com.arangodb.internal.velocystream.internal.VstConnectionSync (com.arangodb.async.internal.velocystream.VstConnectionAsync and com.arangodb.internal.velocystream.internal.VstConnectionSync are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @62dc1d21)
	at com.arangodb.internal.velocystream.VstCommunicationSync.execute(VstCommunicationSync.java:40)
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:138)
	at com.arangodb.internal.velocystream.VstProtocol.execute(VstProtocol.java:46)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)
	at com.arangodb.internal.net.ExtendedHostResolver.resolveFromServer(ExtendedHostResolver.java:127)
	at com.arangodb.internal.net.ExtendedHostResolver.resolve(ExtendedHostResolver.java:85)
	at com.arangodb.internal.net.FallbackHostHandler.confirm(FallbackHostHandler.java:80)
	at com.arangodb.internal.net.DirtyReadHostHandler.confirm(DirtyReadHostHandler.java:70)
	at com.arangodb.internal.velocystream.VstCommunication.connect(VstCommunication.java:97)
	at com.arangodb.internal.velocystream.VstCommunication.execute(VstCommunication.java:137)
	at com.arangodb.async.internal.ArangoExecutorAsync.lambda$execute$2(ArangoExecutorAsync.java:69)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by wajda** [comment]
After a deeper investigation it turned out that the previously placed workaround didn't actually solve the issue, but rather concealed it. The above exception occurs in the Arango active failover mechanism. So even though the previous workaround allowed the primary requests to succeed, the active failover remained non-functional.

Considering the above I've decided to not proceed with the aforementioned workaround, but rather address the underlying issue in the ArangoDB Java Driver - arangodb/arangodb-java-driver#377
