### ISSUE TITLE
java.lang.NoSuchMethodError: za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter.notifyEntities(Ljava/lang/String;Ljava/util/List;)V

### ISSUE THREAD

**Issue by rsaw4** [AbsaOSS/spline#923]
i know atlas is no longer in latest version, but any idea on this error?
I am using spark 2.4, atlas 1.1, spline 0.3.9
and have added following jars to spark folder: 

spline-bundle-2_4-0.3.9.jar
spline-core-spark-adapter-2.4-0.3.9.jar
spline-core-spark-adapter-api-0.3.9.jar
spline-model-0.3.9.jar
spline-persistence-api-0.3.9.jar
spline-persistence-atlas-0.3.9.jar
atlas-common-0.8-incubating.jar
atlas-intg-1.1.0.jar
atlas-notification-0.8-incubating.jar
atlas-typesystem-0.8-incubating.jar

```
java.lang.NoSuchMethodError: za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter.notifyEntities(Ljava/lang/String;Ljava/util/List;)V
        at za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter.protected$notifyEntities(AtlasDataLineageWriter.scala:48)
        at za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter$$anonfun$store$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(AtlasDataLineageWriter.scala:48)
        at za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter$$anonfun$store$1$$anonfun$apply$mcV$sp$1.apply(AtlasDataLineageWriter.scala:43)
        at za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter$$anonfun$store$1$$anonfun$apply$mcV$sp$1.apply(AtlasDataLineageWriter.scala:43)
        at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2$$anon$4.block(ExecutionContextImpl.scala:48)
        at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
        at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2.blockOn(ExecutionContextImpl.scala:45)
        at scala.concurrent.package$.blocking(package.scala:123)
        at za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter$$anonfun$store$1.apply$mcV$sp(AtlasDataLineageWriter.scala:43)
        at za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter$$anonfun$store$1.apply(AtlasDataLineageWriter.scala:41)
        at za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter$$anonfun$store$1.apply(AtlasDataLineageWriter.scala:41)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by wajda** [comment]
It requires `org.apache.atlas:atlas-notification:1.0.0`

**Comment by wajda** [comment]
Please refer [pom.xml](https://github.com/AbsaOSS/spline/blob/release/0.3.9/persistence/atlas/pom.xml) for details.

I'm closing the ticket as Spline 0.3 isn't maintained anymore. Please try using other resources for getting help about unsupported Spline versions.
