### ISSUE TITLE
org.apache.atlas.hook.AtlasHook - Adding entity for type: spark_endpoint_dataset java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by rsaw4** [AbsaOSS/spline#924]
I am using spark 2.4, atlas 1.1, spline 0.3.9

```
2021-07-01 10:27:03,827 [ForkJoinPool-1-worker-1] INFO  org.apache.atlas.hook.AtlasHook - Adding entity for type: spark_endpoint_dataset
java.lang.AbstractMethodError
        at org.json4s.DefaultFormats$class.$init$(Formats.scala:352)
        at org.apache.atlas.typesystem.json.InstanceSerialization$$anon$1.<init>(InstanceSerialization.scala:339)
        at org.apache.atlas.typesystem.json.InstanceSerialization$.<init>(InstanceSerialization.scala:339)
        at org.apache.atlas.typesystem.json.InstanceSerialization$.<clinit>(InstanceSerialization.scala)
        at org.apache.atlas.typesystem.json.InstanceSerialization.toJson(InstanceSerialization.scala)
        at org.apache.atlas.hook.AtlasHook.notifyEntities(AtlasHook.java:99)
        at za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter.protected$notifyEntities(AtlasDataLineageWriter.scala:45)
        at za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter$$anonfun$store$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(AtlasDataLineageWriter.scala:45)
        at za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter$$anonfun$store$1$$anonfun$apply$mcV$sp$1.apply(AtlasDataLineageWriter.scala:43)
        at za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter$$anonfun$store$1$$anonfun$apply$mcV$sp$1.apply(AtlasDataLineageWriter.scala:43)
        at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2$$anon$4.block(ExecutionContextImpl.scala:48)
        at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
        at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$2.blockOn(ExecutionContextImpl.scala:45)
        at scala.concurrent.package$.blocking(package.scala:123)
        at za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter$$anonfun$store$1.apply$mcV$sp(AtlasDataLineageWriter.scala:43)
        at za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter$$anonfun$store$1.apply(AtlasDataLineageWriter.scala:41)
        at za.co.absa.spline.persistence.atlas.AtlasDataLineageWriter$$anonfun$store$1.apply(AtlasDataLineageWriter.scala:41)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by cerveada** [comment]
Please note that Spline version 0.3 has reached the **End-Of-Life** and is not maintained anymore.

I can't spend much time on this, but from the log, I would say it's an binary incompatibility issue. Probably atlas is expecting different json4s version then is on class path.
